import {esc} from './data.js?v=overhead-unbilled-1';
export function arrivalDriverMarkup(state,worker,job,date){
 const rows=state.vehicleBookings.filter(b=>b.job===job&&b.date===date),own=rows.find(b=>b.driver===worker),available=rows.filter(b=>!b.driver||b.driver===worker);
 const absences=(state.extras?.absences||[]).filter(a=>a.worker_id===worker&&a.date===date&&['approved','pending'].includes(a.status));
 const cancellation=absences.length?'<fieldset class="full arrival-absence"><legend>Dnešní dovolená nebo volno</legend><p>'+absences.map(a=>esc(state.extras.absenceTypes?.find(t=>t.id===a.type_id)?.name||'Volno')+' · '+esc(a.hours)+' h'+(a.start_time?' · '+esc(a.start_time.slice(0,5))+'–'+esc(a.end_time?.slice(0,5)||''):'')).join('<br>')+'</p><label><input type="checkbox" name="cancel_absences" value="'+esc(absences.map(a=>a.id).join(','))+'" required> Zrušit uvedené volno pro dnešní den a zaznamenat příchod</label><p class="subtle">Zruší se celý dnešní záznam volna, včetně případné části dne. Ostatní dny zůstanou zachované. Pokud se příchod nepodaří uložit, volno se nezruší.</p></fieldset>':'';
 return cancellation+'<fieldset class="arrival-driver full"><legend>Řidič vozidla</legend><div class="arrival-driver-options"><label><input type="radio" name="driver_choice" value="yes" '+(own?'checked':'')+' '+(!available.length?'disabled':'')+'> Jsem řidič</label><label><input type="radio" name="driver_choice" value="no" '+(!own?'checked':'')+'> Nejsem řidič</label></div><label data-arrival-vehicle '+(!own?'hidden':'')+'>Které auto řídíte?<select name="driver_booking" '+(!own?'disabled':'')+'>'+rows.map(b=>{const v=state.vehicles.find(v=>v.id===b.vehicle);return '<option value="'+esc(b.id)+'" '+(b.id===(own||available[0])?.id?'selected':'')+' '+(b.driver&&b.driver!==worker?'disabled':'')+'>'+esc((v?.name||'Vozidlo')+(v?.plate?' · '+v.plate:'')+(b.driver&&b.driver!==worker?' — řidič '+b.driverName:''))+'</option>'}).join('')+'</select></label><p class="subtle">'+(!rows.length?'Na tuto zakázku a den není naplánované auto. Pokud ho řídíte, požádejte dispečera o doplnění vozidla.':!available.length?'Naplánovaná auta již mají jiné řidiče. Změnu domluvte s dispečerem.':'Volba platí pro tuto zakázku a den. Při „Nejsem řidič“ se zruší pouze vaše přiřazení.')+'</p></fieldset>';
}
export function driverChoice(form){const f=form instanceof FormData?form:new FormData(form);return {cancel_absences:String(f.get('cancel_absences')||'').split(',').filter(Boolean),driver_choice:f.get('driver_choice'),booking:f.get('driver_choice')==='yes'?f.get('driver_booking'):null}}
document.addEventListener('change',e=>{if(e.target.name!=='driver_choice')return;const box=e.target.closest('.arrival-driver'),yes=box.querySelector('[value=yes]').checked;box.querySelector('[data-arrival-vehicle]').hidden=!yes;box.querySelector('select').disabled=!yes;box.querySelector('select').required=yes});
