import {esc} from './data.js?v=jobs-read-1';
import {roleLabel} from './worker-accounts.js?v=finance-detail-1';
const tables={saas_assignments:'Plán pracovníka',saas_vehicle_bookings:'Plán vozidla',saas_attendance:'Docházka',saas_jobs:'Zakázka',saas_workers:'Pracovník',saas_vehicles:'Vozidlo',saas_fueling:'Tankování',saas_finance_entries:'Finanční záznam',saas_absences:'Volno',saas_day_notes:'Poznámka v plánu',saas_skills:'Odbornost',saas_companies:'Nastavení firmy',saas_members:'Oprávnění účtu',saas_invitations:'Pozvánka'};
const actions={delete_job:'Smazání zakázky',finance_close_month:'Uzavření finančního měsíce',finance_job_kind:'Změna režijního zařazení zakázky',finance_job_status:'Změna uzavření zakázky',admin_direct_time:'Ruční zadání nebo oprava docházky',attendance_update:'Úprava docházky',attendance_delete:'Smazání docházky',attendance_correction:'Schválená oprava docházky',fuel_update:'Úprava tankování',fuel_delete:'Smazání tankování',vehicle_delete:'Smazání vozidla',delete_worker:'Smazání pracovníka',remove_assignment:'Odebrání pracovníka z plánu',vehicle_booking_remove:'Odebrání zakázky z vozidla',day_note_delete:'Smazání poznámky',note_link:'Přiřazení poznámky k zakázce',field_job:'Nová zakázka z realizace',merge_jobs:'Sloučení zakázek',invoice_unlock:'Odemknutí vyfakturovaných dnů',peer_departure:'Převzetí času odchodu kolegy',card_pin_changed:'Změna PINu tankovací karty',purchase_save:'Uložení nákupu',purchase_delete:'Smazání nákupu',purchase_invoice:'Přiřazení nákupů k fakturaci',supplier_save:'Uložení dodavatele',job_task:'Změna úkolu zakázky',finance_save:'Uložení finančního záznamu',finance_delete:'Smazání finančního záznamu',finance_rate:'Změna hodinové sazby',finance_budget:'Změna cenové nabídky',finance_invoice:'Změna fakturace'};
const fields={review_note:'Vyjádření dispečinku',month:'Měsíc',overhead:'Režijní zakázka',valid_from:'Platnost od',dates:'Fakturované dny',document_url:'Odkaz na doklad',finance_closed:'Finančně uzavřeno',finance_invoiced:'Vyfakturováno',total_amount:'Celková částka',purchased_at:'Datum nákupu',name:'Název',title:'Úkol',worker_id:'Pracovník',job_id:'Zakázka',assigned_job_id:'Přiřazená zakázka',vehicle_id:'Vozidlo',lead_worker_id:'Vedoucí',date:'Den',start_time:'Začátek práce',planned_hours:'Plán hodin',hours:'Hodiny',arrived_at:'Příchod',left_at:'Odchod',break_minutes:'Přestávka (minuty)',recorded_at:'Čas tankování',note:'Poznámka',reason:'Důvod',description:'Popis',address:'Adresa',contact:'Kontakt',phone:'Telefon',email:'E-mail',plate:'SPZ',color:'Barva',group_name:'Skupina',status:'Stav',active:'Aktivní',enabled:'Povoleno plánování',role:'Oprávnění',amount:'Částka',price:'Cena',rate:'Hodinová sazba',hourly_rate:'Hodinová sazba',labor_price:'Cena práce',material_price:'Cena materiálu',transport_price:'Cena dopravy',kind:'Druh',type:'Typ',type_id:'Druh volna',done:'Splněno',deleted:'Odebráno',completed_name:'Splnil',completed_at:'Čas splnění',from_attendance:'Vytvořeno z docházky',field_created:'Zadáno z realizace',card_number:'Číslo karty',card_number_snapshot:'Karta při tankování',supplier:'Dodavatel',supplier_name:'Dodavatel',supplier_id:'Dodavatel',order_number:'Číslo objednávky',order_date:'Datum objednávky',order_url:'Odkaz na objednávku',invoice_id:'Fakturace',document_number:'Číslo dokladu',reference:'Doklad',cost_category:'Kategorie nákladu',category:'Kategorie',quantity:'Množství',unit_price:'Jednotková cena',line_items:'Položky',allocations:'Rozdělení mezi zakázky',purchase:'Nákup',purchases:'Nákupy',documents:'Dokumenty',url:'Odkaz',locked:'Uzamčeno',casual:'Brigádník',daily_hours:'Pracovní den (hodiny)',workdays:'Pracovní dny',leave_allowance_hours:'Nárok na dovolenou (hodiny)',vacation_day_hours:'Den dovolené (hodiny)',active_from:'Aktivní od',active_to:'Aktivní do',hidden_from:'Skrytý od',work_day_hours:'Délka pracovního dne',day_start:'Začátek dne',tolerance:'Tolerance příchodu (minuty)',allow_other_jobs:'Výběr jiné zakázky',default_hours:'Výchozí počet hodin',time_from:'Čas od',time_to:'Čas do',phase:'Fáze',sort_order:'Pořadí',estimated:'Odhad',skills:'Odbornosti',skill_id:'Odbornost'};
const enums={proposed:'Navrženo',rate:'Hodinová sazba',pending:'Čeká na schválení',approved:'Schváleno',rejected:'Zamítnuto',active:'Aktivní',invoiced:'Vyfakturováno',closed:'Uzavřeno',archived:'Archivováno',merged:'Sloučeno',labor:'Práce',material:'Materiál',transport:'Doprava',other:'Ostatní',unclassified:'Nerozděleno',invoice:'Fakturace',budget:'Cenová nabídka',change:'Změnový list',overhead:'Režijní',productive:'Výdělečná',vacation:'Dovolená'};
const reasons={'Potvrzene odstraneni testovaci zakazky':'Potvrzené odstranění testovací zakázky','Odstraneni testovaciho pracovnika':'Odstranění testovacího pracovníka','Potvrzene smazani pracovnika':'Potvrzené smazání pracovníka','Ukol zakazky upraven':'Úkol zakázky upraven','Ukol zakazky odebran':'Úkol zakázky odebrán','Ukol zakazky splnen':'Úkol zakázky splněn','Ukol vracen k reseni':'Úkol vrácen k řešení','Ulozeni dodavatele':'Uložení dodavatele','Smazani poznamky':'Smazání poznámky','Prirazeni poznamky pracovnika k zakazce':'Přiřazení poznámky pracovníka k zakázce','Odstraneni prirazeni, dochazka zachovana':'Odebrání z plánu; docházka zůstala zachovaná','Uvolneni vozidla po odebrani posledniho pracovnika':'Uvolnění vozidla po odebrání posledního pracovníka','Odebrani zakazky z planu vozidla':'Odebrání zakázky z plánu vozidla','Zahrnuti podilu nakupu do fakturace':'Zahrnutí podílu nákupu do fakturace','Zahrnuti nakupu do fakturace':'Zahrnutí nákupu do fakturace','Nova zakazka z realizace ke kontrole':'Nová zakázka z realizace ke kontrole'};
const uuid=/^[\da-f]{8}-[\da-f-]{27}$/i;
const date=v=>{const d=new Date(v);return Number.isNaN(+d)?String(v):d.toLocaleString('cs-CZ',{timeZone:'Europe/Prague',...(String(v).length===10?{year:'numeric',month:'numeric',day:'numeric'}:{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})})};
export function auditMarkup(rows,state){
 const lookup=(kind,id)=>state[kind]?.find(x=>x.id===id)?.name;
 function value(v,k,depth=0){if(v==null||v==='')return '—';if(typeof v==='boolean')return v?'Ano':'Ne';if(k==='role')return roleLabel(v);const kind={worker_id:'workers',lead_worker_id:'workers',job_id:'jobs',assigned_job_id:'jobs',vehicle_id:'vehicles',skill_id:'skills'}[k];if(kind)return lookup(kind,v)||'Již nedostupný záznam';if(k==='type_id')return state.extras?.absenceTypes?.find(x=>x.id===v)?.name||'Druh volna již není dostupný';if(k==='workdays'&&Array.isArray(v))return v.map(x=>['Ne','Po','Út','St','Čt','Pá','So'][x]||'').join(', ');if(typeof v==='number')return v.toLocaleString('cs-CZ')+(['amount','price','rate','hourly_rate','unit_price','total_amount'].includes(k)?' Kč':'');if(['start_time','time_from','time_to','day_start'].includes(k)&&/^\d{2}:\d{2}/.test(v))return String(v).slice(0,5);if(depth>3)return 'Podrobnosti položky';if(Array.isArray(v))return v.map(x=>value(x,k,depth+1)).join('; ')||'Žádné položky';if(typeof v==='object')return Object.entries(v).filter(([f])=>fields[f]).map(([f,x])=>fields[f]+': '+value(x,f,depth+1)).join(', ')||'Záznam bez uložených podrobností';if(uuid.test(String(v)))return 'Navázaný záznam';if(/^\d{4}-\d{2}-\d{2}(T|$)/.test(v))return date(v);return enums[v]||String(v)}
 return rows.map(r=>{const [table,op]=String(r.record_type||'').split(':'),title=actions[table]||(tables[table]?tables[table]+(op==='INSERT'?' – přidáno':op==='DELETE'?' – smazáno':op==='UPDATE'?' – upraveno':' – změna'):'Změna záznamu');const removed=op==='DELETE'||['attendance_delete','fuel_delete','vehicle_delete','delete_worker','delete_job','day_note_delete','purchase_delete','finance_delete','remove_assignment','vehicle_booking_remove'].includes(table);const b=r.before_value,a=r.after_value,old=b&&typeof b==='object'&&!Array.isArray(b)?b:{},next=a&&typeof a==='object'&&!Array.isArray(a)?a:{};
 const keys=[...new Set([...Object.keys(old),...Object.keys(next)])].filter(k=>fields[k]&&(!b||!a||JSON.stringify(old[k])!==JSON.stringify(next[k])));
 const context=a||b||{},name=context.name||context.title||[lookup('workers',context.worker_id),lookup('jobs',context.job_id),context.date?value(context.date,'date'):null].filter(Boolean).join(' · ')||lookup(({saas_jobs:'jobs',saas_workers:'workers',saas_vehicles:'vehicles'})[table],r.record_id)||'';
 let reason=reasons[r.reason]||r.reason||'';if(/^Prevzato od zaznamu /.test(reason))reason='Čas převzatý podle docházky kolegy';if(/^Cil: /.test(reason))reason='Sloučeno do zakázky: '+(lookup('jobs',reason.slice(5))||'již nedostupná zakázka');
 const details=keys.length?'<table class="simple-table"><thead><tr><th>Údaj</th><th>Před změnou</th><th>Po změně</th></tr></thead><tbody>'+keys.map(k=>'<tr><th>'+esc(fields[k])+'</th><td>'+esc(value(old[k],k))+'</td><td>'+esc(a?(k==='status'&&next.review_note==='Zrušeno dispečinkem'?'Zrušeno':value(next[k],k)):removed?'Odstraněno':'Nezaznamenáno')+'</td></tr>').join('')+'</tbody></table>':Array.isArray(a)||Array.isArray(b)?'<p>'+esc(value(a||b,'items'))+'</p>':'<p>U tohoto záznamu nejsou uložené podrobnosti změny.</p>';
 return '<details style="padding:12px 0;border-bottom:1px solid #ddd"><summary><strong>'+esc(title)+'</strong>'+(name?' · '+esc(name):'')+'<br><small>'+esc(date(r.at))+' · '+esc(r.actor_name||(r.actor?'Uživatel bez dostupného jména':'Automatická změna'))+'</small></summary>'+(reason?'<p>'+esc(reason)+'</p>':'')+details+(!a&&!removed&&b?'<p class="subtle">Nový stav nebyl v tomto starším záznamu uložen.</p>':'')+'</details>';
 }).join('')||'<p>Zatím nejsou zaznamenané žádné změny.</p>';
}
