import {client} from './connection.js?v=details-1';
import {esc} from './data.js?v=details-1';
export function installCompanyMail(ctx){
 const dialog=document.createElement('dialog');dialog.className='operations-dialog';dialog.id='company-mail-dialog';dialog.innerHTML='<form><h2>E-maily firmy</h2><div class="mail-fields form-grid"></div><p class="mail-message" role="status"></p><div class="toolbar"><button type="button" data-mail="close" class="secondary">Zavřít</button><button class="primary">Uložit nastavení</button></div></form>';document.body.append(dialog);
 let config=null,company=null,epoch=0;
 const input=(name,title,value='',extra='')=>`<label>${title}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
 async function edge(action,body={}){const {data,error}=await client.functions.invoke('company-mail',{body:{company,action,...body}});if(error)throw Error('E-mailové propojení zatím není dostupné. Zkontrolujte nasazení funkce company-mail.');if(data.error)throw Error(data.error);return data}
 async function open(){const turn=epoch;company=ctx.company();const {data,error}=await client.rpc('saas_mail_settings_get',{c:company});if(error)throw Error(error.message);if(turn!==epoch)return;config=data;dialog.querySelector('.mail-message').textContent='';dialog.querySelector('.mail-fields').innerHTML=`<label>Způsob odesílání<select name="provider"><option value="platform">Společný odesílatel aplikace</option><option value="microsoft">Microsoft 365</option><option value="smtp">Vlastní SMTP</option></select></label>${input('sender_name','Jméno odesílatele',config.sender_name,'maxlength="120"')}${input('reply_to','Adresa pro odpovědi',config.reply_to,'type="email"')}<div class="full mail-microsoft"><p>Připojený účet: <strong>${esc(config.sender_address||'Žádný')}</strong></p><button type="button" data-mail="connect" class="secondary">Připojit Microsoft 365</button><p class="subtle">Přihlásíte se u Microsoftu. Heslo k Microsoft 365 se do plánovače nezadává. Jméno odesílatele zde určuje připojená schránka.</p></div><div class="full form-grid mail-smtp">${input('smtp_host','SMTP server',config.details?.host||'')}${input('smtp_user','Přihlašovací jméno',config.details?.user||'')}${input('smtp_password','Heslo (prázdné = ponechat uložené)','','type="password" autocomplete="new-password" maxlength="2000"')}${input('sender_address','E-mail odesílatele',config.sender_address,'type="email"')}<p class="subtle full">Připojení SSL na portu 465. Microsoft 365 připojte tlačítkem Microsoft výše.</p></div><p class="full">Stav: <strong>${esc({unconfigured:'Vyžaduje nastavení',configured:'Uloženo, zatím neověřeno',connected:'Připojeno',error:'Poslední test se nepodařil'}[config.status]||config.status)}</strong>${config.last_test_at?' · poslední test '+esc(new Date(config.last_test_at).toLocaleString('cs-CZ')):''}</p><p class="full">${esc({pending:'Test čeká ve frontě',sending:'Test se odesílá',sent:'Test předán poštovní službě',failed:'Test se nepodařil',uncertain:'Výsledek testu není jistý; zkontrolujte schránku'}[config.last_test_status]||'')}</p><div class="full"><button type="button" data-mail="test" class="secondary">Poslat test na můj e-mail</button><p class="subtle">Test odešle uložené nastavení na e-mail vašeho účtu. Doručení proběhne při nejbližší kontrole serveru.</p></div>`;
  const select=dialog.querySelector('[name=provider]');select.value=config.provider;select.onchange=()=>{dialog.querySelector('.mail-microsoft').hidden=select.value!=='microsoft';dialog.querySelector('.mail-smtp').hidden=select.value!=='smtp'};select.onchange();if(!dialog.open)dialog.showModal();
 }
 const settings=()=>{const f=new FormData(dialog.querySelector('form'));return{provider:String(f.get('provider')),sender_name:String(f.get('sender_name')),reply_to:String(f.get('reply_to')),sender_address:String(f.get('sender_address'))}};
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=dialog.querySelector('button.primary');b.disabled=true;try{const f=new FormData(e.currentTarget);await edge('save',{revision:config.revision,settings:settings(),smtp:{host:f.get('smtp_host'),port:465,user:f.get('smtp_user'),password:f.get('smtp_password')}});await open();dialog.querySelector('.mail-message').textContent='Nastavení bylo uloženo.'}catch(e){dialog.querySelector('.mail-message').textContent=e.message}finally{b.disabled=false}};
 dialog.addEventListener('click',async e=>{const b=e.target.closest('[data-mail]');if(!b)return;const action=b.dataset.mail;if(action==='close'){dialog.close();return}b.disabled=true;try{if(action==='connect'){const result=await edge('connect',{revision:config.revision,settings:settings()});const url=new URL(result.url);if(url.origin!=='https://fesvutrdfduoyqljxsuz.supabase.co')throw Error('Neplatné přesměrování.');location.assign(url.href)}else if(action==='test'){const {error}=await client.rpc('saas_mail_test',{c:company});if(error)throw error;dialog.querySelector('.mail-message').textContent='Test je ve frontě. Za chvíli zkontrolujte e-mail a znovu otevřete tento přehled.'}}catch(e){dialog.querySelector('.mail-message').textContent=e.message}finally{b.disabled=false}});
 dialog.addEventListener('close',()=>{dialog.querySelector('[name=smtp_password]')&&(dialog.querySelector('[name=smtp_password]').value='')});
 document.addEventListener('click',e=>{if(e.target.closest('[data-op=company-mail]'))open().catch(e=>ctx.message(e.message))});
 return {reset:()=>{epoch++;dialog.close();dialog.querySelector('.mail-fields').replaceChildren();config=null;company=null}};
}


