export const client=window.supabase.createClient('https://fesvutrdfduoyqljxsuz.supabase.co','sb_publishable_Om8S97cQEw0RPaEDMEAl4w_IRBd9SLD');
const maps={skills:['saas_skills',{id:'id',name:'name',active:'active'}],workers:['saas_workers',{id:'id',name:'name',email:'email',card:'card_number',skills:'skills',phone:'phone',hiddenFrom:'hidden_from'}],jobs:['saas_jobs',{id:'id',name:'name',color:'color',address:'address',estimated:'estimated',skill:'skill_id',documents:'documents',contact:'contact',phone:'phone',lead:'lead_worker_id',note:'note',phase:'phase',defaultHours:'default_hours',timeFrom:'time_from',timeTo:'time_to'}],vehicles:['saas_vehicles',{id:'id',name:'name',plate:'plate',type:'type',seats:'people_capacity',capacity:'capacity',note:'note'}],assignments:['saas_assignments',{id:'id',worker:'worker_id',job:'job_id',date:'date',planned:'planned_hours',start:'start_time',fromAttendance:'from_attendance'}],vehicleBookings:['saas_vehicle_bookings',{id:'id',job:'job_id',vehicle:'vehicle_id',date:'date',hours:'hours'}],attendance:['saas_attendance',{id:'id',worker:'worker_id',job:'job_id',start:'arrived_at',end:'left_at',breakMinutes:'break_minutes'}],fuel:['saas_fueling',{id:'id',worker:'worker_id',vehicle:'vehicle_id',at:'recorded_at',card:'card_number_snapshot',note:'note'}]};
const companyMap={name:'name',logo:'logo',hours:'work_day_hours',dayStart:'day_start',tolerance:'tolerance',allowOtherJobs:'allow_other_jobs'};
function from(row,map){return Object.fromEntries(Object.entries(map).map(([k,v])=>[k,row[v]]))}
function to(row,map){return Object.fromEntries(Object.entries(map).map(([k,v])=>[v,['skill','lead','hiddenFrom','timeTo'].includes(k)?(row[k]||null):k==='fromAttendance'?(row[k]??false):(row[k]??null)]))}
export function decode(snapshot){const state={company:from(snapshot.company,companyMap),reviewed:[],history:[]};for(const [k,[table,map]]of Object.entries(maps))state[k]=(snapshot.data[table]||[]).map(r=>from(r,map));state.company.dayStart=state.company.dayStart.slice(0,5);for(const a of state.assignments){a.start=(a.start||'07:00').slice(0,5);a.planned=Number(a.planned);a.vehicles=state.vehicleBookings.filter(b=>b.job===a.job&&b.date===a.date).map(b=>b.vehicle)}for(const b of state.vehicleBookings)b.hours=Number(b.hours);for(const w of state.workers){w.card=w.card||'';w.role='worker'}state.company.notifications=snapshot.company.notifications;state.company.logoOriginal=snapshot.company.logo_original;state.company.logoCrop=snapshot.company.logo_crop;for(const j of state.jobs){const raw=snapshot.data.saas_jobs.find(r=>r.id===j.id);Object.assign(j,{status:raw.status,fieldCreated:raw.field_created})}state.extras=snapshot.extras||{};for(const raw of state.extras.workers||[]){const w=state.workers.find(w=>w.id===raw.id);if(w)Object.assign(w,raw);else state.workers.push({id:raw.id,name:raw.name,skills:[],card:'',...raw})}state.workers.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));if(snapshot.membership.role==='foreman'){for(const r of state.extras.teamAssignments||[])if(!state.assignments.some(a=>a.id===r.id))state.assignments.push({...from(r,maps.assignments[1]),vehicles:state.vehicleBookings.filter(b=>b.job===r.job_id&&b.date===r.date).map(b=>b.vehicle)});for(const r of state.extras.teamAttendance||[])if(!state.attendance.some(a=>a.id===r.id))state.attendance.push(from(r,maps.attendance[1]))}return state}
export function operations(before,after,company){const ops=[];for(const key of ['skills','workers','jobs','vehicles','assignments','vehicleBookings']){const [table,map]=maps[key],old=new Map(before[key].map(r=>[r.id,to(r,map)]));if(key==='vehicleBookings')for(const row of before[key])if(!after[key].some(r=>r.id===row.id))ops.push({table,op:'delete',row:{id:row.id}});for(const row of after[key]){const next=to(row,map),previous=old.get(row.id);if(JSON.stringify(previous)!==JSON.stringify(next))ops.push({table,op:previous?'update':'insert',row:next})}}if(JSON.stringify(to(before.company,companyMap))!==JSON.stringify(to(after.company,companyMap)))ops.push({table:'saas_companies',op:'update',row:{id:company,...to(after.company,companyMap)}});return ops}
export function createConnection(){let company=null,snapshot=null,epoch=0;async function rpc(name,args){const {data,error}=await client.rpc(name,args);if(error)throw Error(error.message);return data}return {
 get snapshot(){return snapshot},clear(){epoch++;snapshot=null;company=null},
 async connect(id){const turn=++epoch;company=id;const data=await rpc('saas_snapshot',{target_company:id});if(turn!==epoch)throw Error('Relace se změnila.');data.extras=await rpc('saas_extras',{c:company});if(turn!==epoch)throw Error('Relace se změnila.');snapshot=data;return decode(data)},
 async feature(action,p){const turn=epoch;const data=await rpc('saas_feature',{c:company,expected_version:snapshot.company.version,action,p});if(turn!==epoch)throw Error('Relace se změnila.');snapshot={...data.snapshot,extras:data.extras};return decode(snapshot)},
 async refresh(){return this.connect(company)},
 async save(next){const turn=epoch;const ops=operations(decode(snapshot),next,company);if(!ops.length)return decode(snapshot);const data=await rpc('saas_apply',{target_company:company,expected_version:snapshot.company.version,operations:ops});if(turn!==epoch)throw Error('Relace se změnila.');data.extras=await rpc('saas_extras',{c:company});if(turn!==epoch)throw Error('Relace se změnila.');snapshot=data;return decode(data)},
 async clock(action,job,pause=0){await rpc(action==='arrive'?'saas_clock_in':action==='depart'?'saas_clock_out':'saas_switch_job',action==='depart'?{target_company:company,pause_minutes:pause}:{target_company:company,target_job:job});return this.refresh()},
 async fuel(vehicle,note){await rpc('saas_record_fueling',{target_company:company,target_vehicle:vehicle,fuel_note:note});return this.refresh()},
 async report(month){const d=new Date(month+'-01T12:00:00');d.setMonth(d.getMonth()+1);d.setDate(0);return rpc('saas_hours_report',{target_company:company,date_from:month+'-01',date_to:`${month}-${String(d.getDate()).padStart(2,'0')}`})}
}}

