import {auditMarkup} from './audit-labels.js?v=inline-reports-1';
import {byName} from './selection-order.js?v=selection-1';
import {attendanceChecks} from './checks.js?v=attendance-checks-2';
import {esc,reportRows,localDate} from './data.js?v=overhead-unbilled-1';
export function installExperience(ctx){
 const dialog=document.createElement('dialog');document.body.append(dialog);
 const button=(a,t)=>`<button type="button" data-experience="${a}">${t}</button>`;
 function show(title,body){dialog.innerHTML=`<div class="dialog-heading"><h2>${title}</h2>${button('close','Zavřít')}</div><div class="panel-content">${body}</div>`;if(!dialog.open)dialog.showModal()}
 const key=()=>`planner-preferences:${ctx.user()}`;
 function prefs(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}}
 function apply(){const p=prefs();document.documentElement.dataset.theme=p.theme||'light';document.documentElement.dataset.density=p.density||'normal'}
 function guide(){const role=ctx.role();show('Průvodce plánovačem',`<p><strong>Plán:</strong> Můj plán ukazuje vaše přiřazení. Celý plán ukáže lidi, zakázky a auta vlastní firmy.</p><p><strong>Příchod a odchod:</strong> při příchodu vyberte dnešní zakázku. Jiný čas zadáte ručně${role==='admin'?' přímo':', ke schválení'}.</p><p><strong>Upozornění:</strong> žádosti o opravu a volno najdete pod zvonkem.</p><p><strong>Mobil:</strong> další sekce jsou pod tlačítkem Více.</p>${role==='admin'?'<p><strong>Finance:</strong> nastavte sazby s datem platnosti, ceny a režijní činnosti. Kontrolujte podklady před uzavřením měsíce.</p>':''}<p>Nápovědu můžete kdykoliv spustit znovu.</p>${button('guide-done','Rozumím / přeskočit')}`)}

 function checks(){
  if(!['admin','dispatcher'].includes(ctx.role()))return;
  show('Kontrola docházky','<p>Porovnání minulých plánů se skutečnou docházkou, včetně starších měsíců.</p><div class="form-grid"><label>Od<input type="date" data-check-from></label><label>Do<input type="date" data-check-to></label></div><div data-check-rows></div>');
  const draw=()=>{const s=ctx.state(),rows=attendanceChecks(s,dialog.querySelector('[data-check-from]').value,dialog.querySelector('[data-check-to]').value||undefined);dialog.querySelector('[data-check-rows]').innerHTML=rows.map(r=>{const req=(s.extras?.requests||[]).find(p=>p.status==='pending'&&p.worker_id===r.worker&&p.job_id===r.job&&localDate(p.proposed_start)===r.date),prompt=(s.extras?.attendancePrompts||[]).find(p=>p.worker_id===r.worker&&p.job_id===r.job&&p.date===r.date);return '<section class="op-item"><strong>'+esc(s.workers.find(w=>w.id===r.worker)?.name||'Pracovník')+'</strong> · '+esc(r.date)+'<p>'+esc(s.jobs.find(j=>j.id===r.job)?.name||'Zakázka')+' · '+esc(r.text)+'</p>'+(req?'<p>Návrh čeká na schválení</p><button type="button" data-op="review-request" data-key="'+esc(req.id)+'">Posoudit návrh</button>':(r.assignment?'<button type="button" data-missing-attendance="'+esc(r.assignment)+'">Doplnit / podle kolegy</button>':'<button type="button" data-op="request" data-key="'+esc(r.attendance)+'">Upravit příchod / odchod</button>')+(r.assignment?(prompt?.status==='requested'?'<p>Výzva odeslána — čeká na návrh pracovníka.</p>':'<button type="button" data-check-prompt="'+esc(r.assignment)+'">Vyžádat časy od pracovníka</button>'):'') )+'</section>'}).join('')||'<p>V tomto období nebyly nalezeny chybějící záznamy ani nesrovnalosti.</p>';};
  dialog.querySelectorAll('input').forEach(el=>el.onchange=draw);
  dialog.onclick=e=>{if(e.target.closest('[data-missing-attendance],[data-op]'))dialog.close();const b=e.target.closest('[data-check-prompt]');if(b){dialog.close();ctx.requestAttendance(b.dataset.checkPrompt)}};draw();
 }
 async function act(a){const menu=document.getElementById('dialog');if(menu?.open)menu.close();if(a==='close')dialog.close();if(a==='guide')guide();if(a==='guide-done'){localStorage.setItem('planner-guide:'+ctx.user(),ctx.guideRole());dialog.close()}
 if(a==='preferences'){const p=prefs();show('Vzhled a rozložení',`<form id="experience-prefs"><label>Vzhled<select name="theme"><option value="light">Světlý</option><option value="dark">Tmavý</option></select></label><label>Hustota plánu<select name="density"><option value="normal">Běžná</option><option value="compact">Kompaktní</option></select></label><button>Uložit</button></form>`);const f=dialog.querySelector('form');f.theme.value=p.theme||'light';f.density.value=p.density||'normal';f.onsubmit=e=>{e.preventDefault();localStorage.setItem(key(),JSON.stringify(Object.fromEntries(new FormData(f))));apply();dialog.close()}}
 if(a==='unbilled'){const months=[...new Set([...ctx.state().attendance.map(r=>localDate(r.start).slice(0,7)),...(ctx.state().extras.historicalHours||[]).map(r=>r.date.slice(0,7))])],totals=new Map();for(const month of months)for(const row of reportRows(ctx.state(),{month,billing:'unbilled'}))totals.set(row.job,(totals.get(row.job)||0)+row.hours);show('Nevyfakturovaná práce', '<p>U režie je uvedena pouze část dosud nezahrnutá ve fakturaci výdělečných zakázek daného měsíce.</p>'+([...totals].map(([name,h])=>'<p>'+esc(name)+' · '+h.toFixed(2)+' h</p>').join('')||'<p>Žádné nevyfakturované hodiny.</p>'))}if(a==='checks')checks();if(a==='audit'){const rows=await ctx.audit();show('Historie změn',auditMarkup(rows,ctx.state()))}if(a==='pin'){const pin=await ctx.pin(ctx.me());show('PIN mojí tankovací karty',`<p>PIN se zobrazí pouze na vyžádání.</p><input type="password" readonly value="${esc(pin||'')}" aria-label="PIN">${button('reveal-pin','Zobrazit / skrýt')}`)}
 if(a==='reveal-pin'){const input=dialog.querySelector('input');input.type=input.type==='password'?'text':'password'}
 if(a==='edit-pin'&&ctx.role()==='admin'){show('PIN tankovací karty',`<form id="card-pin-form"><label>Pracovník<select name="worker">${byName(ctx.state().workers).map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}</select></label><label>Nový PIN<input type="password" name="pin" inputmode="numeric" pattern="[0-9]{4,12}" required autocomplete="off"></label><button>Uložit</button><p role="alert"></p></form>`);dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await ctx.pin(e.target.worker.value,e.target.pin.value);dialog.close()}catch(err){e.target.querySelector('p').textContent=err.message}}}
 }
 document.addEventListener('click',e=>{const b=e.target.closest('[data-experience]');if(b)act(b.dataset.experience).catch(e=>ctx.message(e.message))});
 function decorate(page){apply();const nav=document.getElementById('navigation');nav.insertAdjacentHTML('beforeend',button('preferences','Vzhled a rozložení')+button('guide','Nápověda')+(ctx.role()==='admin'?button('audit','Historie změn'):'')+(['admin','dispatcher'].includes(ctx.role())?button('checks','Kontrola docházky')+button('unbilled','Nevyfakturovaná práce'):''));
 if(page==='plan'&&ctx.me())document.getElementById('content').insertAdjacentHTML('afterbegin',button('pin','PIN mojí karty'));
 
 if(localStorage.getItem('planner-guide:'+ctx.user())!==ctx.guideRole()&&!document.querySelector('dialog[open]')){localStorage.setItem('planner-guide:'+ctx.user(),ctx.guideRole());guide()}
 }
 return {decorate,reset(){dialog.close();dialog.innerHTML=''}};
}
