import {costReport} from './costs.js?v=week-plan-2';
import {esc} from './data.js?v=week-plan-2';
export function installFinance(ctx){
 const dialog=document.createElement('dialog');dialog.className='finance-dialog';document.body.append(dialog);let data,from,to;
 const money=n=>n===null?'Neúplné podklady':new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK'}).format(n);
 const input=(n,label,value='',type='text')=>`<label>${label}<input name="${n}" type="${type}" ${type==='number'?'step="0.01"':''} value="${esc(value)}"></label>`;
 const choices=(n,label,rows,value='')=>`<label>${label}<select name="${n}">${rows.map(r=>`<option value="${esc(r.id)}" ${r.id===value?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label>`;
 const button=(action,label,id='')=>`<button type="button" data-finance="${action}" data-id="${id}">${label}</button>`;
 function shell(title,body){dialog.innerHTML=`<div class="dialog-heading"><h2>${title}</h2>${button('close','Zavřít')}</div><div class="panel-content">${body}<p role="alert" id="finance-error"></p></div>`;if(!dialog.open)dialog.showModal()}
 async function open(job){if(!ctx.admin())return;try{data=await ctx.read();const now=new Date();from||=now.toISOString().slice(0,7)+'-01';to||=now.toISOString().slice(0,10);if(job)edit('invoice','',job);else render()}catch(e){ctx.message(e.message)}}
 function render(){const s=ctx.state(),r=costReport(s,data,from,to),whole=costReport(s,data,'1900-01-01','9999-12-31');shell('Finance zakázek',`<form id="finance-period" class="toolbar">${input('from','Od',from,'date')}${input('to','Do',to,'date')}<button>Zobrazit</button></form><p>Částky za práci bez DPH. Režie se rozděluje podle hodin v celém příslušném měsíci. Chybějící sazba znamená neúplný výsledek.</p><div class="toolbar">${button('rate','Sazba pracovníka')}${button('budget','Cena montáže')}${button('change','Změnový list')}${button('invoice','Fakturace práce')}${button('overhead','Další režijní náklad')}${button('kind','Režijní zakázka')}${button('close_month','Uzavřít měsíc')}${button('open_month','Otevřít měsíc')}</div><div class="table-wrap"><table class="simple-table"><thead><tr><th>Zakázka</th><th>Plán h</th><th>Skutečnost h</th><th>Náklad práce</th><th>Režie</th><th>Fakturace období</th><th>Výsledek období</th><th>Cena celkem</th><th>Výsledek proti plánu celé zakázky</th><th>Zbývá fakturovat</th><th>Cena minus skutečné náklady celé zakázky</th><th>Marže období</th></tr></thead><tbody>${r.jobs.filter(j=>j.actualHours||j.plannedHours||j.price!==null).map(j=>`<tr><td>${esc(j.name)}${j.overhead?' · režie':''}<small>${j.missingRates?' · chybí sazba':from.slice(0,7)===to.slice(0,7)&&data.closedMonths.some(m=>m.month.slice(0,7)===from.slice(0,7))?' · uzavřené období':' · předběžné'}</small></td><td>${j.plannedHours.toFixed(2)}</td><td>${j.actualHours.toFixed(2)}</td><td>${money(j.actualCost)}</td><td>${money(j.actualOverhead)}</td><td>${j.partialInvoice?'Faktura zasahuje mimo období':money(j.periodInvoiced)}</td><td>${j.partialInvoice?'—':money(j.actualResult)}</td><td>${j.price===null?'Bez rozpočtu':money(j.price)}</td><td>${money(whole.jobs.find(x=>x.id===j.id)?.plannedResult??null)}</td><td>${j.price===null?'Bez rozpočtu':money(j.price-j.invoiced)}</td><td>${j.price===null?'Bez rozpočtu':whole.jobs.find(x=>x.id===j.id)?.missingRates?'Chybí sazba':money(j.price-(whole.jobs.find(x=>x.id===j.id)?.actualCost||0)-(whole.jobs.find(x=>x.id===j.id)?.actualOverhead||0))}</td><td>${j.actualResult!==null&&j.periodInvoiced>0&&!j.partialInvoice?(j.actualResult/j.periodInvoiced*100).toFixed(1)+' %':'—'}</td></tr>`).join('')}</tbody></table></div><h3>Pracovníci za vybrané období</h3>${r.workers.map(w=>`<p>${esc(s.workers.find(x=>x.id===w.id)?.name||'Pracovník')}: ${w.hours.toFixed(2)} h · ${w.missingRates?'chybí sazba':money(w.cost)}</p>`).join('')}<h3>Záznamy a změnové listy</h3>${data.entries.map(e=>`<p>${esc(e.name||e.kind)} · ${esc(e.valid_from)} · ${money(Number(e.amount))} · ${esc(e.status)} ${button(e.kind,'Upravit',e.id)}</p>`).join('')}<h3>Uzavřené měsíce</h3>${data.closedMonths.map(m=>esc(m.month)).join(', ')||'Žádné'}`);
 dialog.querySelector('#finance-period').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('from')>f.get('to'))return;from=f.get('from');to=f.get('to');render()};
 }
 function edit(kind,id,job){const e=data.entries.find(x=>x.id===id)||{job_id:job},s=ctx.state();let fields='';
 if(kind==='rate')fields+=choices('worker','Pracovník',s.workers,e.worker_id);
 if(['budget','change','invoice','kind'].includes(kind))fields+=choices('job','Zakázka',s.jobs,e.job_id);
 if(kind==='kind')fields+='<label><input type="checkbox" name="overhead"> Režijní činnost (kancelář, sklad, školení…)</label>';
 else if(kind.endsWith('_month'))fields+=input('month','Měsíc',from.slice(0,7),'month')+input('reason','Důvod');
 else{fields+=input('from',kind==='rate'?'Platnost sazby od':'Datum',e.valid_from||from,'date')+input('amount',kind==='rate'?'Náklad za hodinu (Kč)':'Částka za práci bez DPH (Kč)',e.amount??'','number')+input('name',kind==='change'?'Číslo a název změnového listu':'Název / číslo dokladu',e.name||'')+input('note','Poznámka',e.note||'');
 if(kind==='change')fields+=choices('status','Stav',[{id:'proposed',name:'Navrženo'},{id:'approved',name:'Schváleno'},{id:'rejected',name:'Zamítnuto'}],e.status||'proposed')+input('url','Odkaz na změnový list',e.document_url||'','url');
 if(kind==='invoice')fields+='<fieldset><legend>Fakturované dny</legend><div id="invoice-days"></div></fieldset><p id="invoice-preview" class="full"></p>';
 }
 shell('Upravit finanční údaje',`<form id="finance-edit" class="form-grid">${fields}<button class="primary">Uložit</button></form>`);
 const form=dialog.querySelector('form');
 if(kind==='invoice'){const fill=()=>{const job=form.elements.job.value,dates=[...new Set([...s.assignments.filter(a=>a.job===job).map(a=>a.date),...s.attendance.filter(a=>a.job===job).map(a=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Prague'}).format(new Date(a.start))),...(s.extras.historicalHours||[]).filter(a=>a.job_id===job).map(a=>a.date)])].sort();dialog.querySelector('#invoice-days').innerHTML=dates.filter(d=>id?(e.dates||[]).includes(d)||d>=from&&d<=to:d>=from&&d<=to).map(d=>`<label class="checkbox-row"><input name="dates" type="checkbox" value="${d}" ${(e.dates||[]).includes(d)?'checked':''}>${d}</label>`).join('')||'V období nejsou žádné hodiny.'};form.elements.job.onchange=fill;fill();
 const preview=()=>{const f=new FormData(form),days=f.getAll('dates'),job=f.get('job');let hours=0,cost=0,missing=false;for(const day of days){const row=costReport(s,data,day,day).jobs.find(j=>j.id===job);if(row){hours+=row.actualHours;cost+=row.actualCost+row.actualOverhead;missing||=row.missingRates>0}}const amount=Number(f.get('amount'));dialog.querySelector('#invoice-preview').textContent=hours.toFixed(2)+' h · '+(missing?'Chybí nákladová sazba': 'náklady včetně režie '+money(cost)+' · výsledek '+money(amount-cost)+(amount>0?' · marže '+((amount-cost)/amount*100).toFixed(1)+' %':''))};form.addEventListener('input',preview);preview()}
 form.onsubmit=async event=>{event.preventDefault();const f=new FormData(form),p=Object.fromEntries(f);p.kind=kind;if(id)p.id=id;if(kind==='invoice')p.dates=f.getAll('dates');if(kind==='kind')p.overhead=f.has('overhead');if(p.month)p.month+='-01';try{data=await ctx.save(kind==='kind'?'job_kind':kind.endsWith('_month')?kind:'save',p);render()}catch(error){dialog.querySelector('#finance-error').textContent=error.message}};
 }
 dialog.addEventListener('click',e=>{const b=e.target.closest('[data-finance]');if(!b)return;if(b.dataset.finance==='close')dialog.close();else edit(b.dataset.finance,b.dataset.id)});
 return {open};
}
