import {byName,searchText} from './selection-order.js?v=selection-1';
import {costReport} from './costs.js?v=purchases-1';
import {esc,localDate,hours} from './data.js?v=overhead-unbilled-1';
import {financeOverview,money,financeButton as button} from './finance-overview.js?v=selection-1';
import {readJobPreferences,writeJobPreferences} from './job-preferences.js?v=selection-1';
export function installFinance(ctx){
 const dialog=document.createElement('section');dialog.className='finance-page';let generation=0;
 let data,selected='',summary=false,tab='budget',from='',to='',search='',workerId='';
 const today=()=>localDate(new Date().toISOString());
 const input=(n,label,value='',type='text',extra='')=>`<label>${label}<input name="${n}" type="${type}" ${type==='number'?'step="0.01"':''} value="${esc(value??'')}" ${extra}></label>`;
 const choices=(n,label,rows,value='')=>`<label>${label}<select name="${n}">${byName(rows).map(r=>`<option value="${esc(r.id)}" ${r.id===value?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label>`;
 function shell(title,body){dialog.innerHTML=`<div class="page-heading"><h1>${title}</h1>${workerId?button('close','← Pracovníci'):''}</div><div class="panel-content">${body}<p role="alert" id="finance-error"></p></div>`;if(dialog.isConnected)window.scrollTo(0,0)}
 const fail=e=>{const el=dialog.querySelector('#finance-error');if(el)el.textContent=e.message;else ctx.message(e.message)};
 function mount(){const content=document.getElementById('content');if(dialog.parentElement!==content)content.replaceChildren(dialog)}
 function reset(){generation++;data=null;selected=workerId=from=to=search='';summary=false;tab='budget';dialog.replaceChildren()}
 async function begin(job='',worker=''){if(!ctx.admin())return;const request=++generation;workerId=worker;selected=job;tab=job?'invoice':'budget';ctx.navigate('finance');shell('Finance zakázek','<p role="status">Načítám finance…</p>');try{const next=await ctx.read();if(request!==generation)return;data=next;render()}catch(e){if(request!==generation)return;shell('Finance zakázek',button('reload','Zkusit načíst znovu'));fail(e)}}
 async function open(job){return begin(job||'')}
 async function worker(id){return begin('',id)}
 function render(){
  if(workerId){const w=ctx.state().workers.find(w=>w.id===workerId);shell('Hodinové náklady · '+esc(w?.name||''),`<p>Sazby platí od zvoleného dne. Pro novou sazbu přidejte záznam s novým datem.</p>${button('rate','Přidat sazbu')} ${(data.entries||[]).filter(e=>e.kind==='rate'&&e.worker_id===workerId).sort((a,b)=>b.valid_from.localeCompare(a.valid_from)).map(e=>`<article class="finance-record"><strong>${esc(e.valid_from)} · ${money(Number(e.amount))}/h</strong><p>${esc(e.note)}</p>${button('rate','Upravit',e.id)} ${button('delete','Smazat',e.id)}</article>`).join('')||'<p>Sazba zatím není zadaná.</p>'}`);return}
  const prefs=readJobPreferences(ctx.state(),ctx.user());shell('Finance zakázek',financeOverview(ctx.state(),data,prefs,{selected,summary,tab,from,to,search}));
  const filters=dialog.querySelector('#finance-filters');if(filters&&matchMedia('(max-width:700px)').matches)filters.closest('details').open=false;if(filters)filters.onsubmit=event=>{event.preventDefault();const f=new FormData(filters);if(f.get('from')&&f.get('to')&&f.get('from')>f.get('to'))return fail(Error('Datum od musí předcházet datu do.'));from=f.get('from');to=f.get('to');search=f.get('search');for(const key of ['filter','sort','group'])prefs[key]=f.get(key);writeJobPreferences(ctx.state(),ctx.user(),prefs);render()};
 }
 function wireSave(form,action,payload){form.onsubmit=async event=>{event.preventDefault();const save=form.querySelector('button.primary');save.disabled=true;try{const p=payload(new FormData(form));data=await ctx.save(action,p);render()}catch(e){fail(e)}finally{save.disabled=false}}}
 function remove(id){const e=data.entries.find(x=>x.id===id);if(!e)throw Error('Záznam není dostupný.');shell('Smazat finanční záznam',`<p>${esc(e.name||e.kind)} · ${money(Number(e.amount))}</p>${e.kind==='invoice'?'<p>Navázané nákupy se označí jako nezahrnuté. Jeho dny se uvolní k fakturaci, pokud nejsou zahrnuté v jiné fakturaci. Označení celé zakázky jako vyfakturované se zruší.</p>':''}<form>${input('reason','Důvod smazání','','text','required maxlength="500"')}<label class="checkbox-row"><input name="confirmed" type="checkbox" required> Potvrzuji smazání tohoto záznamu</label><div class="toolbar"><button class="primary">Smazat</button>${button('back','Zrušit')}</div></form>`);wireSave(dialog.querySelector('form'),'delete',f=>({id,reason:f.get('reason'),confirmed:f.has('confirmed')}))}
 function jobStatus(job){const j=ctx.state().jobs.find(j=>j.id===job),v=data.jobStates?.find(j=>j.job_id===job)||{closed:j.status==='completed'||j.status==='invoiced',billed:j.status==='invoiced'};shell('Stav zakázky · '+esc(j.name),`<form><label class="checkbox-row"><input type="checkbox" name="closed" ${v.closed?'checked':''}> Zakázka je uzavřená</label><label class="checkbox-row"><input type="checkbox" name="billed" ${v.billed?'checked':''}> Celá zakázka je vyfakturovaná</label><p>Fakturace jednotlivých dnů zůstávají evidované samostatně. Částku fakturace zadáte v záložce Fakturace.</p><div class="toolbar"><button class="primary">Uložit</button>${button('back','Zrušit')}</div></form>`);wireSave(dialog.querySelector('form'),'job_status',f=>({job,closed:f.has('closed'),billed:f.has('billed')}))}
 function edit(kind,id='',job=selected){
  if(kind==='budget'&&!id)id=data.entries.find(e=>e.kind==='budget'&&e.job_id===job)?.id||'';
  const e=data.entries.find(x=>x.id===id)||{job_id:job,worker_id:workerId},s=ctx.state(),itemized=['budget','change','invoice'].includes(kind);let fields='';
  if(kind==='rate')fields+=choices('worker','Pracovník',s.workers,e.worker_id);
  if(['budget','change','invoice','kind'].includes(kind))fields+=choices('job','Zakázka',[...s.jobs].filter(j=>j.status!=='merged'||j.id===e.job_id).sort((a,b)=>a.name.localeCompare(b.name,'cs')),e.job_id);
  if(kind==='kind')fields+=`<label class="checkbox-row"><input type="checkbox" name="overhead" ${data.jobKinds.some(k=>k.job_id===e.job_id&&k.overhead)?'checked':''}> Režijní činnost (kancelář, sklad, školení…)</label>`;
  else if(kind.endsWith('_month'))fields+=input('month','Měsíc',(from||today()).slice(0,7),'month','required')+input('reason','Důvod','','text','required');
  else{
   fields+=input('from',kind==='rate'?'Platnost sazby od':'Datum',e.valid_from||today(),'date','required');
   if(itemized)fields+='<fieldset class="finance-items"><legend>Rozpis ceny bez DPH (volitelné)</legend><div id="finance-items"></div><button type="button" id="add-finance-item">Přidat položku</button><p>Vyplňte jen potřebné položky. Součet doplní celkovou cenu. Bez rozpisu zadejte přímo celkovou částku.</p></fieldset>';
   fields+=input('amount',kind==='rate'?'Náklad za hodinu (Kč)':'Celková částka bez DPH (Kč)',e.amount??'','number','required')+input('name',kind==='change'?'Číslo a název změnového listu':'Název / číslo dokladu',e.name||'')+input('note','Poznámka',e.note||'');
   if(itemized)fields+=input('url','Odkaz na doklad',e.document_url||'','url');
   if(kind==='change')fields+=choices('status','Stav',[{id:'proposed',name:'Navrženo'},{id:'approved',name:'Schváleno'},{id:'rejected',name:'Zamítnuto'}],e.status||'proposed');
   if(kind==='invoice')fields+=`<fieldset class="full"><legend>Fakturované dny</legend><div class="toolbar">${input('daysFrom','Dny od',from||'','date')}${input('daysTo','Dny do',to||'','date')}</div><button type="button" data-days="all">Vybrat vše</button><button type="button" data-days="none">Zrušit výběr</button><div id="invoice-days"></div>${id?'<p>Odebrané dny se uvolní k nové fakturaci. Tím se zruší případné označení celé zakázky jako vyfakturované.</p>':''}</fieldset><fieldset class="full"><legend>Nákupy k zahrnutí do fakturace</legend><p>Zaškrtnutí pouze označí nákup. Fakturovanou částku vyplňte samostatně; nákupní cena se nepřičítá.</p><div id="invoice-purchases"></div></fieldset><p id="invoice-preview" class="full"></p>`;
  }
  shell('Upravit '+({budget:'cenovou nabídku',invoice:'fakturaci',change:'změnový list',rate:'hodinovou sazbu',kind:'režijní činnost',overhead:'režijní náklad'}[kind]||'období'),`<form id="finance-edit" class="form-grid">${fields}<div class="toolbar full"><button class="primary">Uložit</button>${button('back','Zrušit')}</div></form>`);
  const form=dialog.querySelector('form');if(form.elements.job&&(id||selected))form.elements.job.disabled=true;if(form.elements.worker&&(id||workerId))form.elements.worker.disabled=true;
  let updatePreview=()=>{};
  const lineValues=()=>[...form.querySelectorAll('.finance-item')].filter(row=>row.querySelector('[data-item-amount]').value!=='').map(row=>({name:row.querySelector('[data-item-name]').value.trim(),amount:Number(row.querySelector('[data-item-amount]').value)}));
  if(itemized){const list=form.querySelector('#finance-items'),total=()=>{const items=lineValues();form.elements.amount.readOnly=items.length>0;if(items.length)form.elements.amount.value=(items.reduce((n,x)=>n+x.amount,0)).toFixed(2);updatePreview()};const add=x=>{const row=document.createElement('div');row.className='finance-item';row.innerHTML=`<input aria-label="Název položky" data-item-name value="${esc(x.name)}" maxlength="200"><input aria-label="Částka položky" data-item-amount type="number" step="0.01" ${kind!=='change'?'min="0"':''} value="${esc(x.amount??'')}"><button type="button" aria-label="Odebrat položku">×</button>`;row.querySelector('button').onclick=()=>{row.remove();total()};row.oninput=total;list.append(row)};(e.line_items?.length?e.line_items:[{name:'Práce'},{name:'Materiál'},{name:'Doprava'}]).forEach(add);form.querySelector('#add-finance-item').onclick=()=>add({name:''});total()}
  if(kind==='invoice'){
   let chosen=new Set(e.dates||[]);const jobId=()=>e.id?e.job_id:form.elements.job.value;
   const fill=()=>{const job=jobId();if(form.dataset.purchaseJob!==job){form.dataset.purchaseJob=job;form.querySelector('#invoice-purchases').innerHTML=(data.purchases||[]).filter(p=>p.job_id===job&&(!p.invoice_id||p.invoice_id===id)).map(p=>`<label class="checkbox-row"><input type="checkbox" name="purchases" value="${esc(p.id)}" ${p.invoice_id===id?'checked':''}>${esc(p.description)} · ${esc(data.suppliers?.find(s=>s.id===p.supplier_id)?.name||'')} · ${money(Number(p.amount))} náklad${!p.invoice_id?' · dosud nezahrnuto':''}</label>`).join('')||'<p>Žádné nezahrnuté nákupy.</p>';}const other=new Set(data.entries.filter(x=>x.kind==='invoice'&&x.job_id===job&&x.id!==id).flatMap(x=>x.dates||[])),dates=[...new Set([...(e.dates||[]),...s.assignments.filter(a=>a.job===job).map(a=>a.date),...s.attendance.filter(a=>a.job===job).map(a=>localDate(a.start)),...(s.extras.historicalHours||[]).filter(a=>a.job_id===job).map(a=>a.date)])].sort();form.querySelector('#invoice-days').innerHTML=dates.filter(d=>(!form.elements.daysFrom.value||d>=form.elements.daysFrom.value)&&(!form.elements.daysTo.value||d<=form.elements.daysTo.value)).map(d=>`<label class="checkbox-row"><input name="dates" type="checkbox" value="${d}" ${chosen.has(d)?'checked':''} ${other.has(d)?'disabled':''}>${esc(d)}${other.has(d)?' · v jiné fakturaci':''}</label>`).join('')||'<p>V období nejsou žádné dny.</p>';updatePreview()};
   // Calculate the monthly overhead once; selecting days does not recalculate every job repeatedly.
   const full=costReport(s,data,'1900-01-01','9999-12-31'),rates=data.entries.filter(x=>x.kind==='rate').sort((a,b)=>b.valid_from.localeCompare(a.valid_from)),daysCost=new Map();for(const a of [...s.attendance.filter(a=>a.end).map(a=>({worker:a.worker,job:a.job,date:localDate(a.start),hours:hours(a)})),...(s.extras.historicalHours||[]).map(a=>({worker:a.worker_id,job:a.job_id,date:a.date,hours:Number(a.hours)}))]){const k=a.job+'|'+a.date,v=daysCost.get(k)||{hours:0,cost:0,missing:false},rate=rates.find(x=>x.worker_id===a.worker&&x.valid_from<=a.date),pool=full.pools.get('actual'+a.date.slice(0,7)),overhead=data.jobKinds.some(j=>j.job_id===a.job&&j.overhead);v.hours+=a.hours;v.cost+=(rate?Number(rate.amount)*a.hours:0)+(!overhead&&pool?.hours?pool.cost*a.hours/pool.hours:0);v.missing||=(!rate&&a.hours>0)||(!overhead&&!!pool?.missing);daysCost.set(k,v)}
   updatePreview=()=>{let h=0,c=0,missing=false;for(const date of chosen){const x=daysCost.get(jobId()+'|'+date);if(x){h+=x.hours;c+=x.cost;missing||=x.missing}}const picked=new Set(new FormData(form).getAll('purchases'));c+=(data.purchases||[]).filter(p=>picked.has(p.id)).reduce((n,p)=>n+Number(p.amount),0);const a=Number(form.elements.amount.value);form.querySelector('#invoice-preview').textContent=chosen.size+' vybraných dnů · '+h.toFixed(2)+' h · '+(missing?'Chybí nákladová sazba':'náklady práce, režie a vybraných nákupů '+money(c)+' · předběžný výsledek '+money(a-c)+(a>0?' · marže '+((a-c)/a*100).toFixed(1)+' %':''))};
   form.querySelector('#invoice-purchases').onchange=()=>updatePreview();form.querySelector('#invoice-days').onchange=event=>{if(event.target.checked)chosen.add(event.target.value);else chosen.delete(event.target.value);updatePreview()};form.elements.job.onchange=()=>{chosen.clear();fill()};for(const name of ['daysFrom','daysTo'])form.elements[name].onchange=fill;form.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{form.querySelectorAll('[name=dates]:not(:disabled)').forEach(c=>{c.checked=b.dataset.days==='all';if(c.checked)chosen.add(c.value);else chosen.delete(c.value)});updatePreview()});form.elements.amount.oninput=updatePreview;form.selectedInvoiceDays=()=>[...chosen].sort();fill();
  }
  wireSave(form,kind==='kind'?'job_kind':kind.endsWith('_month')?kind:'save',f=>{const p=Object.fromEntries(f);p.kind=kind;if(form.elements.job?.disabled)p.job=form.elements.job.value;if(form.elements.worker?.disabled)p.worker=form.elements.worker.value;if(id){p.id=id;if(e.job_id)p.job=e.job_id;if(e.worker_id)p.worker=e.worker_id}if(kind==='invoice'){if(p.daysFrom&&p.daysTo&&p.daysFrom>p.daysTo)throw Error('Zkontrolujte období.');p.dates=form.selectedInvoiceDays();p.purchases=f.getAll('purchases')}if(kind==='kind')p.overhead=f.has('overhead');if(p.month)p.month+='-01';if(itemized){p.line_items=lineValues();if(p.line_items.some(x=>!x.name||!Number.isFinite(x.amount)))throw Error('Vyplňte název každé oceněné položky.')}delete p.daysFrom;delete p.daysTo;return p});
 }
 dialog.addEventListener('click',event=>{const el=event.target.closest('[data-finance]');if(!el)return;try{const a=el.dataset.finance,id=el.dataset.id,job=el.dataset.job||selected;if(a==='purchases'){ctx.purchases(job);return}if(a==='close'){ctx.navigate('workers');return}if(a==='reload'){begin(selected,workerId);return}if(a==='overview'){selected='';render()}else if(a==='back')render();else if(a==='job'){selected=id;tab='budget';render()}else if(a==='tab'){tab=id;render()}else if(a==='summary'){summary=!summary;render()}else if(a==='clear-period'){from=to='';render()}else if(a==='delete')remove(id);else if(a==='job_status')jobStatus(job);else edit(a,id,job)}catch(e){fail(e)}});
 return {open,worker,mount,reset};
}
