import {client} from './connection.js?v=shared-groups-1';
import {esc} from './data.js?v=overhead-unbilled-1';
export function installJobTasks({remote,state}){
 const d=document.createElement('dialog');d.className='operations-dialog';d.style.cssText='width:min(680px,94vw);max-height:90dvh;overflow:auto';document.body.append(d);let job=null,data=null,epoch=0,busy=false;
 const close=()=>{epoch++;job=null;data=null;d.close();d.replaceChildren()};
 d.addEventListener('cancel',close);
 async function call(action='read',p={}){const company=remote.companyId,n=epoch;busy=true;d.querySelectorAll('button,input,textarea').forEach(b=>b.disabled=true);try{const r=await client.rpc('saas_job_tasks_api',{c:company,j:job,action,p});if(n!==epoch||company!==remote.companyId)return;if(r.error)throw Error(r.error.message);data=r.data;paint();if(action!=='read')window.dispatchEvent(new Event('planner-data-changed'));}catch(e){if(n===epoch){const s=d.querySelector('[role=status]');if(s)s.textContent=e.message;}}finally{if(n===epoch){busy=false;d.querySelectorAll('button,input,textarea').forEach(b=>b.disabled=false);if(data&&!data.can_check)d.querySelectorAll('[data-task-check]').forEach(b=>b.disabled=true);}}}
 function paint(){d.innerHTML=`<header style="display:flex;justify-content:space-between;gap:12px"><h2>Úkoly · ${esc(state().jobs.find(j=>j.id===job)?.name||'Zakázka')}</h2><button type="button" data-task-close>Zavřít</button></header><p>Úkoly platí pro celou zakázku, nezávisle na dni v plánovači.</p><p><strong>${data.tasks.filter(t=>t.done).length} z ${data.tasks.length} splněno</strong> <button type="button" data-task-refresh>Obnovit</button></p><div role="status" aria-live="polite"></div><div>${data.tasks.map(t=>`<section style="padding:14px 0;border-bottom:1px solid #dbe4ef"><label style="display:flex;align-items:flex-start;gap:12px"><input type="checkbox" data-task-check="${t.id}" ${t.done?'checked':''} ${data.can_check?'':'disabled'}><span style="white-space:pre-wrap;overflow-wrap:anywhere;${t.done?'text-decoration:line-through':''}">${esc(t.title)}</span></label>${t.done?`<p class="subtle">Splnil/a ${esc(t.completed_name||'Uživatel')} · ${esc(new Date(t.completed_at).toLocaleString('cs-CZ'))}</p>`:''}${data.can_edit?`<button type="button" data-task-edit="${t.id}">Upravit</button> <button type="button" data-task-remove="${t.id}">Odebrat</button>`:''}</section>`).join('')||'<p>Zatím žádné úkoly.</p>'}</div>${data.can_edit?'<form data-task-form style="margin-top:20px"><label>Nový úkol<textarea name="title" maxlength="500" required style="width:100%"></textarea></label><button class="primary" type="submit">Přidat úkol</button><button type="button" data-task-cancel hidden>Zrušit úpravu</button></form>':''}`;}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-job-tasks]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(!remote.companyId)return;epoch++;job=b.dataset.jobTasks;data=null;d.innerHTML='<p>Načítám úkoly…</p><div role="status"></div><button data-task-close>Zavřít</button>';if(!d.open)d.showModal();call();},true);
 d.addEventListener('click',e=>{if(e.target.closest('[data-task-close]'))return close();if(busy)return;if(e.target.closest('[data-task-refresh]'))return call();if(e.target.closest('[data-task-cancel]'))return paint();const edit=e.target.closest('[data-task-edit]'),remove=e.target.closest('[data-task-remove]');if(edit){const t=data.tasks.find(t=>t.id===edit.dataset.taskEdit),f=d.querySelector('form');f.dataset.id=t.id;f.elements.title.value=t.title;f.querySelector('[type=submit]').textContent='Uložit úkol';f.querySelector('[data-task-cancel]').hidden=false;f.elements.title.focus();}if(remove){const t=data.tasks.find(t=>t.id===remove.dataset.taskRemove);if(confirm('Odebrat úkol „'+t.title+'“?'))call('remove',{id:t.id,revision:t.revision});}});
 d.addEventListener('change',e=>{const id=e.target.dataset.taskCheck;if(!id||busy)return;const t=data.tasks.find(t=>t.id===id);call('check',{id,revision:t.revision,done:e.target.checked});});
 d.addEventListener('submit',e=>{e.preventDefault();if(busy)return;const f=e.target,t=data.tasks.find(t=>t.id===f.dataset.id);call('save',{id:t?.id,revision:t?.revision,title:f.elements.title.value});});
 return {reset:close};
}
