import {billingBadge} from './job-preferences.js?v=jobs-read-1';
import {avatar,glyph,teamMarkup,plannedTime} from './daily-details.js?v=jobs-read-1';
import {esc,dateKey,safeColor} from './data.js?v=jobs-read-1';
import {contactMarkup} from './plan-usability.js?v=jobs-read-1';
let date=dateKey(new Date()),filter='all',search='',sheet;
const E=esc;
const button=(action,text,active=false)=>`<button type="button" data-mobile="${action}" class="${active?'primary':'secondary'}">${text}</button>`;
const op=(a,text,id)=>`<button type="button" data-op="${a}" data-key="${E(id)}" class="secondary">${text}</button>`;
function shift(n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);date=dateKey(d)}
function collides(rows){return rows.some((a,i)=>rows.slice(i+1).some(b=>{const min=s=>{const [h,m]=String(s||'07:00').split(':').map(Number);return h*60+m};return min(a.start)<min(b.start)+Number(b.planned)*60&&min(b.start)<min(a.start)+Number(a.planned)*60}))}
export function renderMobileDaily(ctx){
 const {state:s,scope,view,manager,me}=ctx,root=document.getElementById('content');if(view==='vehicles'&&filter==='collision')filter='all';
 const mine=(j,d)=>s.assignments.some(a=>a.worker===me&&a.job===j&&a.date===d);
 const resources=s[view].filter(w=>scope==='all'||(view==='workers'?w.id===me:s.vehicleBookings.some(b=>b.vehicle===w.id&&b.date===date&&mine(b.job,b.date)))).filter(w=>!w.hiddenFrom||date<w.hiddenFrom);
 const data=resources.map(w=>{const rows=view==='workers'?s.assignments.filter(a=>a.worker===w.id&&a.date===date):s.vehicleBookings.filter(b=>b.vehicle===w.id&&b.date===date&&(scope==='all'||mine(b.job,b.date))).map(b=>({...b,planned:b.hours,start:'',booking:true}));return {w,rows,collision:view==='workers'&&collides(rows)}}).filter(r=>view!=='workers'||r.rows.length||r.w.enabled!==false&&(!r.w.active_from||date>=r.w.active_from)&&(!r.w.active_to||date<=r.w.active_to));
 const monday=new Date(date+'T12:00:00');monday.setDate(monday.getDate()-(monday.getDay()||7)+1);
 root.innerHTML=`<div class="mobile-daily"><h1>${scope==='mine'?'Můj plán':'Plán firmy'}</h1><div class="daily-scopes"><button data-action="plan-scope" data-id="mine" class="${scope==='mine'?'primary':'secondary'}">Můj plán</button><button data-action="plan-scope" data-id="all" class="${scope==='all'?'primary':'secondary'}">Celá firma</button></div><div class="daily-scopes"><button data-action="view-workers" class="${view==='workers'?'primary':'secondary'}">Pracovníci</button><button data-action="view-vehicles" class="${view==='vehicles'?'primary':'secondary'}">Vozidla</button></div><div class="daily-date"><div class="daily-date-line">${button('prev','‹')}<strong>${new Date(date+'T12:00:00').toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'numeric'})}</strong>${button('next','›')}${button('today','Dnes')}</div><div class="daily-week">${Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return button('date:'+dateKey(d),d.toLocaleDateString('cs-CZ',{weekday:'short'})+'<br>'+d.getDate(),dateKey(d)===date)}).join('')}</div></div><label class="daily-search">${view==='workers'?'Najít pracovníka':'Najít vozidlo'}<input type="search" value="${E(search)}"></label><div class="daily-filters">${button('filter:all','Všichni '+data.length,filter==='all')}${button('filter:empty','Bez plánu '+data.filter(r=>!r.rows.length).length,filter==='empty')}${view==='workers'?button('filter:collision','Kolize '+data.filter(r=>r.collision).length,filter==='collision'):''}</div><div class="daily-people"></div></div>`;
 const list=root.querySelector('.daily-people');
 function draw(){const visible=data.filter(r=>r.w.name.toLocaleLowerCase('cs').includes(search.toLocaleLowerCase('cs'))&&(filter==='all'||filter==='empty'&&!r.rows.length||filter==='collision'&&r.collision));
 list.innerHTML=visible.map(({w,rows,collision})=>`<section class="daily-person"><div class="daily-person-title"><div class="daily-person-name">${view==='workers'?avatar(w.name):glyph('car')}<strong>${E(w.name)}</strong></div>${manager?`<button data-schedule="${E(w.id)}">+ Naplánovat</button>`:''}</div>${collision?'<p class="daily-warning">Souběh plánů — zkontrolujte časy</p>':''}${rows.map(a=>{const j=s.jobs.find(j=>j.id===a.job);return `<article class="daily-card" style="--job-color:${safeColor(j?.color)}"><button class="daily-open" data-detail="${E(a.id)}"><strong>${E(j?.name||'Zakázka')}</strong><span>${glyph('clock')}${a.start?E(plannedTime(a))+' · ':''}${E(a.planned)} h ${a.booking?'vozidla':'plán'}</span><span>${glyph('car')}${E(a.booking?w.plate||'':(a.vehicles||[]).map(id=>s.vehicles.find(v=>v.id===id)?.name).filter(Boolean).join(' · ')||'Bez vozidla')}</span></button>${billingBadge(s,a)}${teamMarkup(s,a)}<div class="daily-card-actions"><button data-detail="${E(a.id)}">${glyph('phone')} Kontakt</button><button data-detail="${E(a.id)}">Více …</button></div></article>`}).join('')||'<p class="daily-empty">Bez plánu</p>'}${(s.extras?.absences||[]).filter(a=>a.worker_id===w.id&&a.date===date&&a.status!=='rejected').map(a=>`<p class="daily-warning">${E(s.extras.absenceTypes?.find(t=>t.id===a.type_id)?.name||'Volno')} · ${E(a.hours)} h${a.status==='pending'?' · čeká na schválení':''}</p>`).join('')}${(s.extras?.notes||[]).filter(n=>n.worker_id===w.id&&n.date===date||rows.some(a=>n.job_id===a.job&&n.date===date)).map(n=>`<div class="daily-note">${E(n.note)}${manager?'<div>'+op('edit-note','Upravit',n.id)+op('delete-note','Smazat',n.id)+'</div>':''}</div>`).join('')}${manager&&view==='workers'?op('note','+ Poznámka','worker|'+w.id+'|'+date):''}</section>`).join('')||'<p class="daily-empty">Pro tento výběr nejsou žádné záznamy.</p>';
 }
 draw();root.querySelector('input').oninput=e=>{search=e.target.value;draw()};
 root.querySelector('.mobile-daily').onclick=e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.mobile){const [a,v]=b.dataset.mobile.split(':');if(a==='prev')shift(-1);if(a==='next')shift(1);if(a==='today')date=dateKey(new Date());if(a==='date')date=v;if(a==='filter')filter=v;ctx.render();}
 if(b.dataset.schedule)ctx.schedule({worker:view==='workers'?b.dataset.schedule:null,vehicle:view==='vehicles'?b.dataset.schedule:null,date,mobileNew:true});
 if(b.dataset.detail){const a=data.flatMap(r=>r.rows).find(a=>a.id===b.dataset.detail);if(!a)return;const j=s.jobs.find(j=>j.id===a.job);sheet??=document.body.appendChild(document.createElement('dialog'));sheet.className='daily-sheet';sheet.innerHTML=`<button class="daily-close" aria-label="Zavřít">×</button>${contactMarkup(j)}<p class="daily-sheet-time">${glyph('clock')}${E(data.find(r=>r.rows.includes(a))?.w.name||'')} · ${E(date)} · ${E(plannedTime(a))} · ${E(a.planned)} h plán</p>${teamMarkup(s,a,true)}${manager&&!a.booking?'<button class="primary" data-edit>Upravit / přesunout</button><button data-copy>Kopírovat</button>'+op('note','Poznámka zakázky','job|'+a.job+'|'+date)+(ctx.admin?op('remove-assignment','Odebrat z plánu',a.id):''):''}`;sheet.onclick=e=>{const b=e.target.closest('button');if(!b)return;sheet.close();if(b.hasAttribute('data-edit'))ctx.edit(a.id);if(b.hasAttribute('data-copy'))ctx.schedule(a)};sheet.showModal();}
 };
}

