import {esc,DEMO_DAY,time,fmtHours,uid} from './data.js?v=mail-2';
import {workbook,download} from './xlsx.js?v=mail-2';
const $=s=>document.querySelector(s),E=esc;
const button=(a,t,id='')=>`<button type="button" class="secondary" data-op="${a}" data-key="${E(id)}">${t}</button>`;
const input=(n,l,v='',type='text',attrs='')=>`<label>${l}<input name="${n}" type="${type}" value="${E(v)}" ${attrs}></label>`;
const select=(n,l,rows,value='')=>`<label>${l}<select name="${n}">${rows.map(r=>`<option value="${E(r.id)}" ${r.id===value?'selected':''}>${E(r.name)}</option>`).join('')}</select></label>`;
const check=(n,l,on=false)=>`<label class="op-check"><input type="checkbox" name="${n}" ${on?'checked':''}>${l}</label>`;
const dt=v=>v?new Date(new Date(v)-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
export function daysBetween(from,to){const out=[];let d=new Date(from+'T12:00:00');const end=new Date(to+'T12:00:00');if(!Number.isFinite(+d)||!Number.isFinite(+end)||d>end)throw Error('Zkontrolujte období.');while(d<=end){out.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`);d.setDate(d.getDate()+1);if(out.length>366)throw Error('Vyberte nejvýše jeden rok.')}return out}
export function workday(day,week=[1,2,3,4,5]){const d=new Date(day+'T12:00:00'),y=d.getFullYear();if(!week.includes(d.getDay()||7))return false;if(['01-01','05-01','05-08','07-05','07-06','09-28','10-28','11-17','12-24','12-25','12-26'].includes(day.slice(5)))return false;const a=y%19,b=Math.floor(y/100),c=y%100,h=(19*a+b-Math.floor(b/4)-Math.floor((b-Math.floor((b+8)/25)+1)/3)+15)%30,l=(32+2*(b%4)+2*Math.floor(c/4)-h-c%4)%7,m=Math.floor((a+11*h+22*l)/451),n=h+l-7*m+114,e=new Date(y,Math.floor(n/31)-1,n%31+1,12);return ![-2,1].some(x=>{const t=new Date(e);t.setDate(t.getDate()+x);return +t===+d})}
export function installOperations(ctx){
 const state=()=>ctx.state(),extra=()=>state().extras||{},manager=()=>ctx.manager(),name=(table,id)=>state()[table]?.find(x=>x.id===id)?.name||'—';
 const dialog=document.createElement('dialog');dialog.className='operations-dialog';dialog.innerHTML='<form><div class="panel-heading"><h2></h2><button type="button" data-op="dismiss" aria-label="Zavřít">×</button></div><div class="op-fields form-grid"></div><p class="op-error" role="alert"></p><div class="toolbar"><button type="button" data-op="dismiss" class="secondary">Zavřít</button><button class="primary op-save">Uložit</button></div></form>';document.body.append(dialog);let submit=null,focus=null;
 function show(title,html,save,label='Uložit'){focus=document.activeElement;dialog.querySelector('.op-fields').onchange=null;dialog.querySelector('h2').textContent=title;dialog.querySelector('.op-fields').innerHTML=html;dialog.querySelector('.op-error').textContent='';dialog.querySelector('.op-save').hidden=!save;dialog.querySelector('.op-save').textContent=label;submit=save;if(!dialog.open)dialog.showModal()}
 dialog.addEventListener('close',()=>focus?.focus());dialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const b=dialog.querySelector('.op-save');b.disabled=true;try{await submit?.(new FormData(e.currentTarget));dialog.close()}catch(e){dialog.querySelector('.op-error').textContent=e.message}finally{b.disabled=false}});
 const run=(a,p)=>ctx.run(a,p),val=(f,k)=>String(f.get(k)||''),num=(f,k)=>Number(f.get(k)),iso=(f,k)=>val(f,k)?new Date(val(f,k)).toISOString():null;
 const workers=()=>manager()?state().workers:state().workers.filter(w=>w.id===ctx.me());
 const jobs=()=>state().jobs.filter(j=>!['invoiced','merged','completed'].includes(j.status));
 const range=()=>input('from','Od',DEMO_DAY,'date','required')+input('to','Do',DEMO_DAY,'date','required');
 function request(id='',job='') {const t=state().attendance.find(t=>t.id===id);show('Žádost o opravu docházky',select('worker','Pracovník',workers(),t?.worker||ctx.me())+select('job','Zakázka',state().jobs,t?.job||job)+input('start','Skutečný příchod',dt(t?.start)||DEMO_DAY+'T07:00','datetime-local','required')+input('end','Skutečný odchod (nechte prázdné, pokud pracujete)',dt(t?.end),'datetime-local')+input('break','Přestávka v minutách',t?.breakMinutes||0,'number','min="0" required')+input('reason','Důvod opravy','','text','required maxlength="1000"'),f=>run('correction_request',{attendance:id||null,worker:val(f,'worker'),job:val(f,'job'),start:iso(f,'start'),end:iso(f,'end'),break:num(f,'break'),reason:val(f,'reason')}),'Odeslat ke schválení')}
 function absence(){show('Volno a nepřítomnost',select('worker','Pracovník',workers(),ctx.me())+select('type','Druh volna',(extra().absenceTypes||[]).filter(t=>t.active))+range()+input('hours','Hodin denně (prázdné = celý pracovní den)','','number','min="0.25" max="24" step="0.25"')+input('start','Částečné volno od (volitelné)','','time')+input('end','Částečné volno do (volitelné)','','time')+input('reason','Poznámka – vidíte ji vy a dispečink','','text','maxlength="1000"')+'<p class="subtle full">Víkendy podle rozvrhu pracovníka a české svátky se nezapočítají. Schválené volno nesmí kolidovat s plánem.</p>',f=>run('absence_request',{worker:val(f,'worker'),type:val(f,'type'),dates:daysBetween(val(f,'from'),val(f,'to')),hours:val(f,'hours'),start:val(f,'start'),end:val(f,'end'),reason:val(f,'reason')}),manager()?'Uložit volno':'Požádat o volno')}
 function schedule(a){show(a?'Kopírovat přiřazení':'Naplánovat více dní',select('job','Zakázka',jobs(),a?.job)+range()+input('start','Začátek',a?.start||'07:00','time','required')+input('hours','Plán hodin na pracovníka',a?.planned??8,'number','min="0" max="24" step="0.25" required')+check('skip','Vynechat víkendy a svátky',true)+`<fieldset class="full"><legend>Pracovníci</legend>${state().workers.map(w=>`<label class="op-check"><input name="workers" type="checkbox" value="${w.id}" ${w.id===a?.worker?'checked':''}>${E(w.name)}</label>`).join('')}</fieldset><fieldset class="full"><legend>Vozidla a jejich vlastní hodiny</legend>${state().vehicles.map(v=>`<div class="op-car"><label><input name="vehicles" type="checkbox" value="${v.id}">${E(v.name)}</label><input aria-label="Hodiny ${E(v.name)}" name="car-${v.id}" type="number" min="0" max="24" step="0.25" value="8"></div>`).join('')}</fieldset><p class="full op-preview subtle">Vyberte období a pracovníky. Před uložením uvidíte kolize.</p>`,async f=>{let dates=daysBetween(val(f,'from'),val(f,'to'));if(f.has('skip'))dates=dates.filter(d=>workday(d));const ws=f.getAll('workers');if(!ws.length||!dates.length)throw Error('Vyberte pracovníka a alespoň jeden pracovní den.');const collisions=state().assignments.filter(x=>ws.includes(x.worker)&&dates.includes(x.date));if(collisions.length&&!f.has('overlap'))throw Error('Existující plán: '+collisions.map(x=>name('workers',x.worker)+' '+x.date).slice(0,5).join(', ')+'. Zkontrolujte přehled a potvrďte souběh.');await run('schedule',{job:val(f,'job'),dates,workers:ws,start:val(f,'start'),hours:num(f,'hours'),vehicles:f.getAll('vehicles').map(id=>({id,hours:num(f,'car-'+id)}))})});const box=dialog.querySelector('.op-preview');function preview(){try{const f=new FormData(dialog.querySelector('form')),dates=daysBetween(val(f,'from'),val(f,'to')).filter(d=>!f.has('skip')||workday(d)),ws=f.getAll('workers'),coll=state().assignments.filter(a=>ws.includes(a.worker)&&dates.includes(a.date));box.innerHTML=`${dates.length} dní × ${ws.length} pracovníků. ${coll.length?'Existující přiřazení: '+coll.map(a=>E(name('workers',a.worker)+' · '+a.date+' · '+name('jobs',a.job))).join('<br>'):'Bez souběhu s existujícím plánem.'}`+(coll.length?check('overlap','Zkontroloval jsem souběh s existujícím plánem'):'')}catch(e){box.textContent=e.message}}dialog.querySelector('.op-fields').onchange=preview;}
 function requests(){const rs=extra().requests||[],abs=extra().absences||[];show('Žádosti a přehled volna',`<div class="full">${button('request','Požádat o opravu')}${button('absence','Volno / žádost o volno')}<h3>Opravy docházky</h3>${rs.map(r=>`<section class="op-item"><strong>${E(name('workers',r.worker_id))} · ${E(name('jobs',r.job_id))}</strong><p>${E(dt(r.proposed_start))} → ${E(dt(r.proposed_end))||'Stále pracuji'} · ${r.break_minutes} min přestávka</p><p>${E(r.reason)} · ${E(status(r.status))}</p>${manager()&&r.status==='pending'?button('review-request','Posoudit',r.id):''}</section>`).join('')||'<p>Žádné žádosti.</p>'}<h3>Volno</h3>${workers().map(w=>{const rows=abs.filter(a=>a.worker_id===w.id&&a.status==='approved'&&a.date.startsWith(DEMO_DAY.slice(0,4))),used=rows.filter(a=>extra().absenceTypes.find(t=>t.id===a.type_id)?.bucket==='vacation').reduce((n,a)=>n+Number(a.hours),0);const last=new Date(Number(DEMO_DAY.slice(0,4)),Number(DEMO_DAY.slice(5,7)),0).getDate(),working=daysBetween(DEMO_DAY.slice(0,7)+'-01',DEMO_DAY.slice(0,7)+'-'+last).filter(d=>workday(d,w.workdays||[1,2,3,4,5])).length;return `<p><strong>${E(w.name)}</strong> · ${working} pracovních dní tento měsíc · dovolená ${fmtHours(used)} / ${fmtHours(w.leave_allowance_hours||0)} h · zbývá ${fmtHours((w.leave_allowance_hours||0)-used)} h</p>`}).join('')}${abs.map(a=>`<section class="op-item">${E(name('workers',a.worker_id))} · ${a.date} · ${E(extra().absenceTypes.find(t=>t.id===a.type_id)?.name||'Nepřítomnost')} · ${fmtHours(a.hours)} h / ${fmtHours(Number(a.hours)/(state().workers.find(w=>w.id===a.worker_id)?.daily_hours||8))} dne · ${E(status(a.status))}<p>${E(a.reason||'')}</p>${manager()&&a.status==='pending'?button('approve-absence','Schválit',a.id)+button('reject-absence','Zamítnout',a.id):''}</section>`).join('')}</div>`,null)}
 const status=s=>({pending:'Čeká na schválení',approved:'Schváleno',rejected:'Zamítnuto'}[s]||s);
 async function handle(a,id){
 if(a==='dismiss'){dialog.close();return}if(a==='request'){request(id);return}if(a==='absence'){absence();return}if(a==='requests'){requests();return}if(a==='schedule'){schedule();return}if(a==='copy'){schedule(state().assignments.find(x=>x.id===id));return}
 if(a==='note'){const [kind,key,date]=id.split('|');show('Poznámka ke dni',input('date','Den',date||DEMO_DAY,'date','required')+`<label class="full">Poznámka<textarea name="note" required maxlength="4000"></textarea></label>`,f=>run('note',{[kind]:key,date:val(f,'date'),note:val(f,'note')}));return}
 if(a==='review-request'){const r=extra().requests.find(r=>r.id===id);show('Posoudit opravu',`<p class="full">${E(name('workers',r.worker_id))}: ${E(r.reason)}</p>`+input('start','Příchod',dt(r.proposed_start),'datetime-local','required')+input('end','Odchod',dt(r.proposed_end),'datetime-local')+input('break','Přestávka',r.break_minutes,'number','min="0" required')+select('status','Rozhodnutí',[{id:'approved',name:'Schválit uvedené časy'},{id:'rejected',name:'Zamítnout'}])+input('reason','Vyjádření dispečinku'),f=>run('correction_review',{id,status:val(f,'status'),start:iso(f,'start'),end:iso(f,'end'),break:num(f,'break'),reason:val(f,'reason')}));return}
 if(a==='approve-absence'||a==='reject-absence'){await run('absence_review',{id,status:a==='approve-absence'?'approved':'rejected'});requests();return}
 if(a==='member-role'){show('Oprávnění účtu',select('role','Role',[{id:'worker',name:'Realizace'},{id:'foreman',name:'Vedoucí realizace'},{id:'dispatcher',name:'Dispečer'},{id:'admin',name:'Administrátor'}]),f=>run('member_role',{worker:id,role:val(f,'role')}));return}
 if(a==='series'){const row=state().assignments.find(x=>x.id===id);show('Úprava přiřazení a série',input('start','Začátek',row.start,'time','required')+input('hours','Plánované hodiny',row.planned,'number','min="0" max="24" step="0.25" required')+check('series','Upravit celou sérii',false)+'<p class="full subtle">Série zahrnuje pracovníky a dny vytvořené společným naplánováním. Docházka zůstává chráněná.</p>'+button('remove-assignment','Zrušit toto přiřazení',id),f=>run('series_edit',{id,series:f.has('series'),start:val(f,'start'),hours:num(f,'hours')}));return}
 if(a==='remove-assignment'){show('Zrušit přiřazení',check('series','Zrušit celou sérii')+check('confirm','Potvrzuji zrušení plánu')+'<p class="full subtle">Záznamy s docházkou nebo uzamčenou fakturací nelze zrušit. Přiřazení vozidel zůstávají samostatná.</p>',f=>{if(!f.has('confirm'))throw Error('Potvrďte zrušení.');return run('assignment_remove',{id,series:f.has('series')})},'Zrušit přiřazení');return}
 if(a==='confirm-job'){await run('job_confirm',{job:id});return}
 if(a==='worker-settings'){const w=state().workers.find(w=>w.id===id);show('Dostupnost a rozvrh · '+w.name,check('casual','Brigádník',w.casual)+check('enabled','Aktivní pro nové plánování',w.enabled!==false)+input('from','Aktivní od',w.active_from||'','date')+input('to','Aktivní do',w.active_to||'','date')+input('hours','Hodin za pracovní den',w.daily_hours||8,'number','min="0.25" max="24" step="0.25" required')+input('allowance','Roční nárok dovolené (hodiny)',w.leave_allowance_hours||0,'number','min="0" required')+`<fieldset class="full"><legend>Pracovní dny</legend>${['Po','Út','St','Čt','Pá','So','Ne'].map((day,i)=>`<label class="op-check"><input type="checkbox" name="week" value="${i+1}" ${(w.workdays||[1,2,3,4,5]).includes(i+1)?'checked':''}>${day}</label>`).join('')}</fieldset>`,f=>run('worker_settings',{worker:id,casual:f.has('casual'),enabled:f.has('enabled'),from:val(f,'from'),to:val(f,'to'),hours:num(f,'hours'),allowance:num(f,'allowance'),workdays:f.getAll('week').map(Number)}));return}
 if(a==='order'){show('Pořadí pracovníků',`<div class="full op-order">${state().workers.map(w=>`<div class="op-item" data-worker="${w.id}">${E(w.name)}${button('up','↑',w.id)}${button('down','↓',w.id)}</div>`).join('')}</div>`,()=>run('worker_order',{workers:[...dialog.querySelectorAll('[data-worker]')].map(e=>e.dataset.worker)}));return}
 if(a==='up'||a==='down'){const row=dialog.querySelector(`[data-worker="${id}"]`);if(a==='up'&&row.previousElementSibling)row.previousElementSibling.before(row);if(a==='down'&&row.nextElementSibling)row.nextElementSibling.after(row);return}
 if(a==='types'){show('Vlastní druhy volna',`<div class="full">${(extra().absenceTypes||[]).map(t=>button('type',E(t.name)+(t.active?'':' (neaktivní)'),t.id)).join('')}${button('type','+ Nový druh')}</div>`,null);return}
 if(a==='type'){const t=extra().absenceTypes.find(t=>t.id===id)||{};show('Druh volna',input('name','Název',t.name||'','text','required maxlength="80"')+input('color','Barva',t.color||'#8195b4','color')+select('unit','Zobrazení',[{id:'hours',name:'Hodiny'},{id:'days',name:'Dny'}],t.unit)+select('bucket','Započítat do',[{id:'other',name:'Ostatní nepřítomnost'},{id:'vacation',name:'Dovolená'},{id:'sick',name:'Sick days'}],t.bucket)+check('approval','Vyžaduje schválení',t.approval!==false)+check('blocks','Blokuje nové plánování',t.blocks!==false)+check('active','Aktivní v nabídce',t.active!==false),f=>run('absence_type',{id:id||null,name:val(f,'name'),color:val(f,'color'),unit:val(f,'unit'),bucket:val(f,'bucket'),approval:f.has('approval'),blocks:f.has('blocks'),active:f.has('active')}));return}
 if(a==='billing'){const j=state().jobs.find(j=>j.id===id),days=[...new Set([...state().assignments.filter(a=>a.job===id).map(a=>a.date),...state().attendance.filter(a=>a.job===id).map(a=>a.start.slice(0,10))])].sort();show('Fakturace · '+j.name,`<fieldset class="full"><legend>Vyberte dny k uzamčení</legend>${days.map(d=>`<label class="op-check"><input name="dates" value="${d}" type="checkbox">${d} ${extra().billing.some(b=>b.job_id===id&&b.date===d&&b.locked)?'· vyfakturováno':''}</label>`).join('')}</fieldset>`+check('whole','Vyfakturovat a archivovat celou zakázku')+`<p class="full subtle">Vyfakturované hodiny budou uzamčené. Odemknutí vyžaduje důvod.</p>${button('unlock','Odemknout fakturaci',id)}`,f=>{if(!f.has('whole')&&!f.getAll('dates').length)throw Error('Vyberte den nebo celou zakázku.');return run('invoice',{job:id,whole:f.has('whole'),dates:f.getAll('dates')})});return}
 if(a==='unlock'){show('Odemknout fakturaci',input('reason','Důvod','','text','required')+input('date','Pouze den (prázdné = vše)','','date'),f=>run('unlock_invoice',{job:id,reason:val(f,'reason'),date:val(f,'date')||null,whole:!val(f,'date')}));return}
 if(a==='merge'){show('Sloučit duplicitní zakázky',select('source','Převést ze zakázky',jobs())+select('target','Do zakázky',jobs())+'<p class="full subtle">Přiřazení, poznámky, docházka a dokumenty přejdou do cílové zakázky. Původní název zůstane v historii. Kolize hodin a uzamčená fakturace sloučení zastaví.</p>'+check('confirmed','Zkontroloval jsem obě zakázky'),f=>{if(!f.has('confirmed'))throw Error('Nejdříve zkontrolujte obě zakázky.');return run('merge_jobs',{source:val(f,'source'),target:val(f,'target')})},'Sloučit');return}
 if(a==='field-job'){show('Nová zakázka při příchodu',input('name','Název','','text','required maxlength="120" list="known-jobs"')+`<datalist id="known-jobs">${jobs().map(j=>`<option value="${E(j.name)}">`).join('')}</datalist>`+input('address','Adresa')+'<p class="full subtle">Nejdříve ověřte, zda zakázka není v nabídce. Novou zakázku označíme dispečinku ke kontrole.</p>',f=>run('field_job',{name:val(f,'name'),address:val(f,'address')}),'Vytvořit a zaznamenat příchod');return}
 if(a==='notifications'){const n=state().company.notifications||{};show('Kdy posílat upozornění',check('plan','Změny plánování e-mailem',n.plan)+check('arrival','Chybějící příchod',n.arrival)+input('arrivalMinutes','Minut po plánovaném příchodu',n.arrivalMinutes||30,'number','min="1" max="1440" required')+check('departure','Chybějící odchod po odchodu kolegy',n.departure)+input('departureMinutes','Minut po odchodu kolegy',n.departureMinutes||30,'number','min="1" max="1440" required')+select('recipient','Komu upozornění',[{id:'both',name:'Pracovník i dispečink'},{id:'worker',name:'Pracovník'},{id:'dispatcher',name:'Dispečink'}],n.recipient)+'<p class="full subtle">Doručování e-mailů vyžaduje aktivní odesílací službu a pravidelnou kontrolu na serveru.</p>',f=>run('notification_settings',{plan:f.has('plan'),arrival:f.has('arrival'),departure:f.has('departure'),arrivalMinutes:num(f,'arrivalMinutes'),departureMinutes:num(f,'departureMinutes'),recipient:val(f,'recipient')}));return}
 if(a==='peer-arrival'||a==='peer-departure'){await run(a==='peer-arrival'?'peer_arrival':'peer_departure',{peer:id});dialog.close();return}
 if(a==='not-arrived'||a==='still-working'){await run(a==='not-arrived'?'not_arrived':'still_working',{job:id});dialog.close();return}
 if(a==='current-arrival'){dialog.close();ctx.standardArrival();return}if(a==='current-departure'){dialog.close();ctx.standardDeparture();return}
 if(a==='logo'){cropLogo();return}
 if(a==='export-absence'){if(!manager())throw Error('Exportuje pouze dispečer.');await ctx.refresh();download(workbook(['Datum','Pracovník','Druh','Hodiny','Dny','Stav'],(extra().absences||[]).map(a=>[a.date,name('workers',a.worker_id),extra().absenceTypes.find(t=>t.id===a.type_id)?.name||'',Number(a.hours),Number(a.hours)/(state().workers.find(w=>w.id===a.worker_id)?.daily_hours||8),status(a.status)]),{name:'Volno',dateColumns:[0],numberColumns:[3,4]}),'volno.xlsx');return}
 }
 document.addEventListener('click',e=>{const b=e.target.closest('[data-op]');if(!b)return;e.preventDefault();handle(b.dataset.op,b.dataset.key||'').catch(e=>{if(dialog.open)dialog.querySelector('.op-error').textContent=e.message;else ctx.message(e.message)})});
 function peer(kind){const active=state().attendance.find(a=>a.worker===ctx.me()&&!a.end),rows=kind==='arrival'?extra().peerArrivals||[]:extra().peerDepartures||[];show(kind==='arrival'?'Zaznamenat příchod':'Zaznamenat odchod',`<div class="full">${rows.map(r=>`<section class="op-item"><strong>${E(r.worker)}</strong> · ${E(name('jobs',r.job))}<p>${kind==='arrival'?'Přišel':'Odešel'} v ${time(r.arrived_at||r.left_at)}</p>${button('peer-'+kind,'Potvrdit stejný čas',r.id)}${kind==='arrival'?button('not-arrived','Ještě jsem nepřišel',r.job):''}</section>`).join('')}${button('current-'+kind,kind==='arrival'?'Přišel jsem teď':'Odcházím teď')}${button('request','Zadat jiný čas – žádost',active?.id||'')}${active?button('still-working','Ještě pracuji',active.job):''}${kind==='arrival'&&state().company.allowOtherJobs?button('field-job','+ Nová zakázka a příchod'):''}</div>`,null)}
 function decorate(page){
  const s=state(),x=extra();if(!s.company)return;let bar=$('#operations-bar');if(!bar){bar=document.createElement('div');bar.id='operations-bar';bar.className='operations-bar';$('#content').before(bar)}bar.innerHTML=button('requests','Žádosti a volno'+((x.requests||[]).filter(r=>r.status==='pending').length?' •':''))+(manager()?button('schedule','Plán na více dní')+button('order','Pořadí pracovníků'):'');
  if(page==='settings')bar.innerHTML+=button('types','Druhy volna')+button('notifications','Upozornění')+button('company-mail','E-maily firmy')+button('logo','Logo a ikona');
  if(page==='jobs'&&manager())bar.innerHTML+=button('merge','Sloučit zakázky');if(page==='reports'&&manager())bar.innerHTML+=button('export-absence','Excel – volno');
  document.querySelectorAll('[data-drop-kind="workers"]').forEach(cell=>{const w=cell.dataset.resource,d=cell.dataset.date;cell.insertAdjacentHTML('beforeend',(x.notes||[]).filter(n=>n.worker_id===w&&n.date===d).map(n=>`<div class="day-note">${E(n.note)}</div>`).join('')+(x.absences||[]).filter(a=>a.worker_id===w&&a.date===d&&a.status!=='rejected').map(a=>`<div class="absence-chip">${E(x.absenceTypes.find(t=>t.id===a.type_id)?.name||'Nepřítomnost')} · ${fmtHours(a.hours)} h${a.status==='pending'?' · žádost':''}</div>`).join('')+(manager()?button('note','+ Poznámka',`worker|${w}|${d}`):''))});
  document.querySelectorAll('.job-card[data-id]').forEach(card=>{const a=s.assignments.find(a=>a.id===card.dataset.id);if(!a)return;card.insertAdjacentHTML('afterend',`<div class="card-tools">${(x.notes||[]).filter(n=>n.job_id===a.job&&n.date===a.date).map(n=>`<div class="day-note">${E(n.note)}</div>`).join('')}${(x.billing||[]).some(b=>b.job_id===a.job&&b.date===a.date&&b.locked)?'<span class="value-pill">Vyfakturováno 🔒</span>':''}${manager()?button('copy','Kopírovat',a.id)+button('series','Série / zrušit',a.id)+button('note','Poznámka zakázky',`job|${a.job}|${a.date}`):''}</div>`)});
  if(page==='workers'&&manager())document.querySelectorAll('[data-action="worker"][data-id]').forEach(b=>{if(b.dataset.id)b.insertAdjacentHTML('afterend',button('worker-settings','Dostupnost a volno',b.dataset.id)+(ctx.admin()?button('member-role','Oprávnění účtu',b.dataset.id):''))});
  if(page==='jobs'&&manager())document.querySelectorAll('[data-action="job"][data-id]').forEach(b=>{if(b.dataset.id)b.insertAdjacentHTML('afterend',button('billing','Fakturace',b.dataset.id)+(s.jobs.find(j=>j.id===b.dataset.id)?.fieldCreated?button('confirm-job','Potvrdit novou zakázku',b.dataset.id):''))});
  if(page==='attendance')document.querySelectorAll('[data-action="correct"]').forEach(b=>{b.removeAttribute('data-action');b.dataset.op='request';b.dataset.key=b.dataset.id;b.textContent='Požádat o opravu'});
  if(page==='plan'&&!manager()){document.querySelectorAll('[data-action=new-assignment], [data-action=prev], [data-action=next], [data-action=weekend], [data-action^=view-]').forEach(b=>b.hidden=true);const snoozed=(kind,job)=>(x.snoozes||[]).some(z=>z.kind===kind&&z.job_id===job&&new Date(z.until_at)>new Date());const active=s.attendance.find(a=>a.worker===ctx.me()&&!a.end);const peers=(active?x.peerDepartures:x.peerArrivals)||[];if(peers.some(r=>!snoozed(active?'departure':'arrival',r.job)))bar.innerHTML+=button(active?'open-departure':'open-arrival',active?'Kolega už odešel – potvrdit čas':'Kolega už je na zakázce – potvrdit čas');}
  updateIcons(s.company.logo);
 }
 document.addEventListener('click',e=>{const a=e.target.closest('[data-op]')?.dataset.op;if(a==='open-arrival')peer('arrival');if(a==='open-departure')peer('departure')});
 let iconValue;async function updateIcons(logo){const signature=(state().company.name||'')+(logo||'');if(iconValue===signature)return;iconValue=signature;for(const rel of ['icon','apple-touch-icon']){let el=document.head.querySelector(`link[rel="${rel}"]`);if(!el){el=document.createElement('link');el.rel=rel;document.head.append(el)}el.href=logo||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22%3E%3Crect width=%2264%22 height=%2264%22 rx=%2214%22 fill=%22%23398aef%22/%3E%3Cpath d=%22M18 34l9 9 20-23%22 fill=%22none%22 stroke=%22white%22 stroke-width=%226%22/%3E%3C/svg%3E'}if(logo&&'serviceWorker' in navigator){try{const registration=await navigator.serviceWorker.register('./sw.js?v=mail-2');await navigator.serviceWorker.ready;const channel=new MessageChannel();channel.port1.onmessage=()=>{let link=document.head.querySelector('link[rel=manifest]');if(!link){link=document.createElement('link');link.rel='manifest';document.head.append(link)}link.href='./company.webmanifest'};(registration.active||navigator.serviceWorker.controller)?.postMessage({type:'brand',name:state().company.name,logo},[channel.port2])}catch{}}}
 function cropLogo(initialFile){show('Logo a ikona firmy',`<label class="full">Vybrat obrázek<input type="file" accept="image/png,image/jpeg,image/webp" id="crop-file"></label><canvas id="crop-preview" width="256" height="256" aria-label="Výřez loga, posun tažením"></canvas><div>${input('zoom','Přiblížení',1,'range','min="1" max="5" step="0.01"')}${input('x','Vodorovný posun',0,'range','min="-1" max="1" step="0.01"')}${input('y','Svislý posun',0,'range','min="-1" max="1" step="0.01"')}<p>Posouvejte obrázek tažením nebo posuvníky. Náhled odpovídá ikoně aplikace.</p></div>`,async()=>{if(!img)throw Error('Vyberte obrázek.');await run('logo',{logo:canvas.toDataURL('image/png'),original,crop:{zoom:Number(z.value),x:Number(px.value),y:Number(py.value)}})});let img=null,original='';const canvas=dialog.querySelector('canvas'),g=canvas.getContext('2d'),z=dialog.querySelector('[name=zoom]'),px=dialog.querySelector('[name=x]'),py=dialog.querySelector('[name=y]');function draw(){if(!img)return;const scale=Math.max(256/img.width,256/img.height)*Number(z.value),w=img.width*scale,h=img.height*scale;g.clearRect(0,0,256,256);g.save();g.beginPath();g.roundRect(0,0,256,256,52);g.clip();g.fillStyle='#fff';g.fillRect(0,0,256,256);g.drawImage(img,(256-w)/2+Number(px.value)*(w-256)/2,(256-h)/2+Number(py.value)*(h-256)/2,w,h);g.restore()}async function load(src){const bitmap=await createImageBitmap(await(await fetch(src)).blob());img?.close();img=bitmap;original=src;draw()}dialog.querySelector('#crop-file').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>4e6||!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('Vyberte PNG, JPEG nebo WebP do 4 MB.');const r=new FileReader();r.onload=()=>load(String(r.result)).catch(e=>dialog.querySelector('.op-error').textContent=e.message);r.readAsDataURL(f)}catch(e){dialog.querySelector('.op-error').textContent=e.message}};[z,px,py].forEach(e=>e.oninput=draw);let start;canvas.onpointerdown=e=>{start={x:e.clientX,y:e.clientY,px:Number(px.value),py:Number(py.value)};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!start)return;px.value=Math.max(-1,Math.min(1,start.px+(e.clientX-start.x)/128));py.value=Math.max(-1,Math.min(1,start.py+(e.clientY-start.y)/128));draw()};canvas.onpointerup=()=>start=null;if(initialFile){const r=new FileReader();r.onload=()=>load(String(r.result)).catch(e=>dialog.querySelector('.op-error').textContent=e.message);if(initialFile.size<=4e6&&['image/png','image/jpeg','image/webp'].includes(initialFile.type))r.readAsDataURL(initialFile);else dialog.querySelector('.op-error').textContent='Vyberte PNG, JPEG nebo WebP do 4 MB.'}else if(state().company.logoOriginal){const c=state().company.logoCrop||{};z.value=c.zoom||1;px.value=c.x||0;py.value=c.y||0;load(state().company.logoOriginal).catch(()=>{})}}
 return {decorate,request,schedule,arrival:()=>peer('arrival'),departure:()=>peer('departure'),cropLogo};
}




