import {byName,searchText} from './selection-order.js?v=selection-1';
import {esc,localDate,safeUrl} from './data.js?v=overhead-unbilled-1';
const money=n=>Number(n).toLocaleString('cs-CZ',{style:'currency',currency:'CZK'});
export function installPurchases(ctx){
 const root=document.createElement('section');root.className='purchases-page';let data={purchases:[],suppliers:[]},job='',supplier='',from='',to='',mode='orders',generation=0;
 const button=(a,label,id='')=>`<button type="button" data-purchase="${a}" data-id="${esc(id)}">${label}</button>`;
 const input=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
 const select=(name,label,rows,value,empty='Vše')=>`<label>${label}<select name="${name}">${empty?`<option value="">${empty}</option>`:''}${byName(rows).map(x=>`<option value="${esc(x.id)}" ${value===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`;
 function shell(title,body){root.innerHTML=`<div class="page-heading"><h1>${esc(title)}</h1></div>${body}<p id="purchase-error" role="alert"></p>`;if(root.isConnected)window.scrollTo(0,0)}
 const fail=e=>{const box=root.querySelector('#purchase-error');if(box)box.textContent=e.message};
 function mount(){const target=document.getElementById('content');if(root.parentElement!==target)target.replaceChildren(root)}
 function reset(){generation++;data={purchases:[],suppliers:[]};job=supplier=from=to='';mode='orders';root.replaceChildren()}
 async function open(id=''){if(!ctx.manager())return;job=id;mode='orders';supplier='';const n=++generation;ctx.navigate('purchases');shell('Nákupy a dodavatelé','<p>Načítám nákupy…</p>');try{const next=await ctx.read();if(n!==generation)return;data=next;render()}catch(e){if(n===generation){shell('Nákupy a dodavatelé',button('reload','Zkusit znovu'));fail(e)}}}
 function render(){const jobs=ctx.state().jobs,rows=data.purchases.filter(x=>(!job||x.job_id===job)&&(!supplier||x.supplier_id===supplier)&&(!from||x.order_date>=from)&&(!to||x.order_date<=to));shell('Nákupy a dodavatelé',`<div class="toolbar">${button('new','+ Přidat nákup')}${button('orders','Objednávky')}${button('suppliers','Dodavatelé')}${button('supplier-new','+ Přidat dodavatele')}</div><details class="finance-filter-panel" open><summary>Filtry objednávek</summary><form id="purchase-filters" class="finance-filters">${select('job','Zakázka',jobs,job)}${select('supplier','Dodavatel',data.suppliers,supplier)}${input('from','Objednáno od',from,'date')}${input('to','Do',to,'date')}<button class="primary">Použít filtry</button>${button('clear','Zrušit filtry')}</form></details><p>${rows.length} nákupů · ${money(rows.reduce((n,x)=>n+Number(x.amount),0))} bez DPH</p>${mode==='suppliers'?`<div class="list-grid">${byName(data.suppliers).filter(x=>!supplier||x.id===supplier).map(s=>{const list=rows.filter(x=>x.supplier_id===s.id);return `<article class="list-card"><h2>${esc(s.name)}</h2><p>${list.length} objednávek · ${money(list.reduce((n,x)=>n+Number(x.amount),0))}</p>${button('supplier','Historie objednávek',s.id)}${button('supplier-edit','Upravit dodavatele',s.id)}</article>`}).join('')||'<p>Zatím žádní dodavatelé. Použijte Přidat dodavatele.</p>'}</div>`:`<div class="list-grid">${byName(rows).map(x=>`<article class="list-card"><h2>${esc(x.description)}</h2><p>${esc(data.suppliers.find(s=>s.id===x.supplier_id)?.name||'')} · ${esc(x.order_number||'Bez čísla objednávky')}</p><p>${esc(x.order_date)} · ${esc(jobs.find(j=>j.id===x.job_id)?.name||'')}</p><strong>${money(x.amount)} bez DPH</strong><p>${x.invoice_id?'✓ Zahrnuto ve fakturaci':'Čeká na zahrnutí do fakturace'}</p>${safeUrl(x.order_url)?`<p><a href="${esc(x.order_url)}" target="_blank" rel="noopener">Otevřít objednávku</a></p>`:''}${x.invoice_id?'<small>Před úpravou musí administrátor odebrat nákup z fakturace.</small>':button('edit','Upravit',x.id)+button('delete','Smazat',x.id)}</article>`).join('')||'<p>Žádné nákupy pro tento výběr.</p>'}</div>`}`);if(matchMedia('(max-width:700px)').matches)root.querySelector('details').open=false;root.querySelector('#purchase-filters').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('from')&&f.get('to')&&f.get('from')>f.get('to'))return fail(Error('Zkontrolujte období.'));job=f.get('job');supplier=f.get('supplier');from=f.get('from');to=f.get('to');render()}}
 function edit(id){mode='orders';const x=data.purchases.find(x=>x.id===id)||{job_id:job,order_date:localDate(new Date().toISOString())};shell(id?'Upravit nákup':'Nový nákup',`<form id="purchase-edit" class="form-grid">${input('job_search','Vyhledat zakázku','','search','placeholder="Pište název nebo adresu…" autocomplete="off"')}${select('job','Zakázka',ctx.state().jobs.filter(j=>j.status!=='merged'),x.job_id,'')}${input('supplier_name','Dodavatel',data.suppliers.find(s=>s.id===x.supplier_id)?.name||'','text','required maxlength="200" list="purchase-suppliers"')}<datalist id="purchase-suppliers">${byName(data.suppliers).map(s=>`<option value="${esc(s.name)}"></option>`).join('')}</datalist><div class="full" id="supplier-results"></div><div class="full">${button('supplier-inline','+ Přidat dodavatele do seznamu')}</div>${input('description','Materiál / popis nákupu',x.description||'','text','required maxlength="500"')}${input('amount','Nákupní cena bez DPH (Kč)',x.amount??'','number','required min="0" max="1000000000" step="0.01"')}${input('number','Číslo objednávky',x.order_number||'','text','maxlength="200"')}${input('date','Datum objednávky',x.order_date,'date','required')}${input('url','Odkaz na objednávku',x.order_url||'','url')}<p class="full">Cena je náklad zakázky. Při zahrnutí do fakturace se prodejní částka zadává samostatně.</p><div class="toolbar full"><button class="primary">Uložit nákup</button>${button('orders','Zrušit')}</div></form>`);saveForm('save',f=>({...Object.fromEntries(f),...(id?{id}:{})}));
 const jobs=byName(ctx.state().jobs.filter(j=>j.status!=='merged')),choice=root.querySelector('[name=job]');choice.required=true;
 root.querySelector('[name=job_search]').oninput=e=>{const selected=choice.value,q=searchText(e.target.value),matches=jobs.filter(j=>j.id===selected||searchText(j.name+' '+(j.address||'')).includes(q));choice.innerHTML=matches.map(j=>`<option value="${esc(j.id)}" ${j.id===selected?'selected':''}>${esc(j.name)}</option>`).join('');choice.value=selected};
 const supplierInput=root.querySelector('[name=supplier_name]');supplierInput.oninput=()=>{const q=searchText(supplierInput.value),results=root.querySelector('#supplier-results');results.replaceChildren();if(!q)return;byName(data.suppliers).filter(s=>searchText(s.name).includes(q)).slice(0,10).forEach(s=>{const b=document.createElement('button');b.type='button';b.textContent=s.name;b.onclick=()=>{supplierInput.value=s.name;results.replaceChildren()};results.append(b)})};
 }
 function supplierForm(id='',inline=false){const current=data.suppliers.find(s=>s.id===id),dialog=document.createElement('dialog');dialog.className='operations-dialog';dialog.innerHTML=`<form><h2>${id?'Upravit dodavatele':'Přidat dodavatele'}</h2>${input('name','Název dodavatele',current?.name||(inline?root.querySelector('[name=supplier_name]').value:''),'text','required maxlength="200"')}<p role="alert"></p><div class="toolbar"><button class="primary">Uložit dodavatele</button><button type="button" data-close>Zrušit</button></div></form>`;root.append(dialog);dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('.primary');b.disabled=true;try{const next=await ctx.save('supplier_save',{id,name:new FormData(e.target).get('name')});data=next;if(inline){root.querySelector('[name=supplier_name]').value=data.suppliers.find(s=>s.id===next.savedSupplier)?.name||'';root.querySelector('#purchase-suppliers').innerHTML=byName(data.suppliers).map(s=>`<option value="${esc(s.name)}"></option>`).join('');dialog.close()}else{dialog.close();mode='suppliers';render()}}catch(error){dialog.querySelector('[role=alert]').textContent=error.message}finally{b.disabled=false}};dialog.showModal();}
 function remove(id){shell('Smazat nákup',`<form id="purchase-edit">${input('reason','Důvod','','text','required maxlength="500"')}<label class="checkbox-row"><input name="confirmed" type="checkbox" required> Potvrzuji smazání nákupu</label><div class="toolbar"><button class="primary">Smazat</button>${button('orders','Zrušit')}</div></form>`);saveForm('delete',f=>({id,reason:f.get('reason'),confirmed:f.has('confirmed')}))}
 function saveForm(action,payload){root.querySelector('#purchase-edit').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button.primary');b.disabled=true;const n=generation;try{const next=await ctx.save(action,payload(new FormData(e.target)));if(n!==generation)return;data=next;render()}catch(error){if(n===generation)fail(error)}finally{b.disabled=false}}}
 root.onclick=e=>{const b=e.target.closest('[data-purchase]');if(!b)return;const a=b.dataset.purchase,id=b.dataset.id;if(a==='supplier-new'||a==='supplier-edit'||a==='supplier-inline'){supplierForm(id,a==='supplier-inline');return}if(a==='new'||a==='edit')edit(id);else if(a==='delete')remove(id);else if(a==='reload')open(job);else{if(a==='supplier'){supplier=id;mode='orders'}if(a==='orders'||a==='suppliers')mode=a;if(a==='clear'){job=supplier=from=to=''}render()}};
 return {open,mount,reset};
}
