import {client} from './connection.js?v=planning-1';
import {esc} from './data.js?v=planning-1';
export function installRegistration(){
 const panel=document.getElementById('login-panel'),login=document.getElementById('login-form');
 const button=document.createElement('button');button.type='button';button.className='secondary';button.id='register-company';button.textContent='Zaregistrovat novou firmu';login.append(button);
 const form=document.createElement('form');form.id='registration-form';form.hidden=true;form.innerHTML='<h1>Nová firma</h1><p>Nejdříve vytvořte svůj účet a potvrďte e-mail.</p><label>Vaše jméno<input name="person" autocomplete="name" required maxlength="120"></label><label>Název firmy<input name="company" autocomplete="organization" required maxlength="120"></label><label>Pracovní e-mail<input name="email" type="email" autocomplete="username" required></label><label>Heslo<input name="password" type="password" autocomplete="new-password" minlength="12" required></label><label>Zopakujte heslo<input name="confirm" type="password" autocomplete="new-password" minlength="12" required></label><p role="alert" class="registration-message"></p><button class="primary">Vytvořit účet</button><button type="button" class="secondary" data-back-login>Zpět na přihlášení</button>';panel.append(form);
 const onboarding=document.createElement('form');onboarding.id='onboarding-form';onboarding.hidden=true;panel.append(onboarding);let resolveCompany=null,created=false;
 function show(which){panel.hidden=false;for(const f of [login,form,onboarding])f.hidden=f!==which}
 button.onclick=()=>show(form);form.querySelector('[data-back-login]').onclick=()=>show(login);
 form.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(form),button=form.querySelector('button'),msg=form.querySelector('.registration-message');if(f.get('password')!==f.get('confirm')){msg.textContent='Hesla se neshodují.';return}button.disabled=true;try{const redirect=new URL(location.href);redirect.search='?register=1';redirect.hash='';const {error}=await client.auth.signUp({email:String(f.get('email')).trim(),password:String(f.get('password')),options:{emailRedirectTo:redirect.href,data:{person_name:String(f.get('person')).trim(),company_name:String(f.get('company')).trim()}}});if(error)throw error;form.querySelector('[name=password]').value='';form.querySelector('[name=confirm]').value='';msg.textContent='Zkontrolujte e-mail a otevřete potvrzovací odkaz. Pokud už účet máte, přihlaste se nebo obnovte heslo.'}catch(e){msg.textContent=e.message}finally{button.disabled=false}});
 async function pickCompany(memberships,session){
  if(memberships.length===1)return memberships[0].company_id;
  show(onboarding);
  if(memberships.length){const {data,error}=await client.from('saas_companies').select('id,name');if(error)throw error;onboarding.innerHTML=`<h1>Vyberte firmu</h1><label>Firma<select name="company">${data.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><button class="primary">Otevřít plánovač</button>`;
   return new Promise(resolve=>{resolveCompany=resolve;onboarding.onsubmit=e=>{e.preventDefault();onboarding.hidden=true;resolve(String(new FormData(onboarding).get('company')));resolveCompany=null}})
  }
  const u=session.user.user_metadata||{};
  onboarding.innerHTML=`<h1>Založit firmu</h1><p>Firma bude mít vlastní prázdný plánovač. Získáte oprávnění administrátora.</p><label>Vaše jméno<input name="person" value="${esc(u.person_name||'')}" required maxlength="120"></label><label>Název firmy<input name="company" value="${esc(u.company_name||'')}" required maxlength="120"></label><label>IČO (volitelné)<input name="ico" inputmode="numeric" pattern="[0-9]{8}" maxlength="8"></label><p class="registration-message" role="alert"></p><button class="primary">Vytvořit firmu</button><button type="button" class="secondary" id="onboarding-logout">Odhlásit se</button><p class="subtle">Máte pozvánku od zaměstnavatele? Použijte odkaz z pozvánky a nezakládejte novou firmu. Logo a odbornosti nastavíte po vytvoření firmy.</p>`;
  onboarding.querySelector('#onboarding-logout').onclick=()=>client.auth.signOut();
  return new Promise(resolve=>{resolveCompany=resolve;onboarding.onsubmit=async e=>{e.preventDefault();const b=onboarding.querySelector('button'),f=new FormData(onboarding);b.disabled=true;try{const {data,error}=await client.rpc('saas_register_company',{company_name:String(f.get('company')).trim(),person_name:String(f.get('person')).trim(),registration_number:String(f.get('ico')).trim()});if(error)throw error;created=true;onboarding.hidden=true;resolve(data);resolveCompany=null}catch(error){onboarding.querySelector('.registration-message').textContent=error.message}finally{b.disabled=false}}})
 }
 return {pickCompany,takeWelcome(){const value=created;created=false;return value},reset(){resolveCompany?.(null);resolveCompany=null;onboarding.hidden=true;show(login)}};
}

