import {esc,fmtHours} from './data.js?v=overhead-unbilled-1';
import {byName} from './selection-order.js?v=selection-1';
import {pragueToday} from './arrival-order.js?v=jobs-read-1';
import {workbook,download} from './xlsx.js?v=jobs-read-1';

export function vacationRows(state,filters){
 return (state.extras?.absences||[]).filter(a=>a.status==='approved'&&state.extras?.absenceTypes?.some(t=>t.id===a.type_id&&t.bucket==='vacation')&&(!filters.worker||a.worker_id===filters.worker)&&(!filters.from||a.date>=filters.from)&&(!filters.to||a.date<=filters.to)).sort((a,b)=>a.date.localeCompare(b.date)||(state.workers.find(w=>w.id===a.worker_id)?.name||'').localeCompare(state.workers.find(w=>w.id===b.worker_id)?.name||'','cs')).map(a=>({date:a.date,worker:state.workers.find(w=>w.id===a.worker_id)?.name||'Pracovník',hours:Number(a.hours)||0}));
}
export function absenceRows(state,filters){
 return (state.extras?.absences||[]).filter(a=>a.status==='approved'&&a.type_id===filters.type&&(!filters.worker||a.worker_id===filters.worker)&&(!filters.from||a.date>=filters.from)&&(!filters.to||a.date<=filters.to)).sort((a,b)=>a.date.localeCompare(b.date)||(state.workers.find(w=>w.id===a.worker_id)?.name||'').localeCompare(state.workers.find(w=>w.id===b.worker_id)?.name||'','cs')).map(a=>({date:a.date,workerId:a.worker_id,worker:state.workers.find(w=>w.id===a.worker_id)?.name||'Pracovník',hours:Number(a.hours)||0}));
}
export function vehicleRows(state,drivers,filters){
 return state.vehicleBookings.filter(b=>(!filters.from||b.date>=filters.from)&&(!filters.to||b.date<=filters.to)&&(!filters.job||b.job===filters.job)&&(!filters.vehicle||b.vehicle===filters.vehicle)&&(!filters.worker||(filters.worker==='none'?!drivers[b.id]:drivers[b.id]===filters.worker))).sort((a,b)=>a.date.localeCompare(b.date)||(state.vehicles.find(v=>v.id===a.vehicle)?.name||'').localeCompare(state.vehicles.find(v=>v.id===b.vehicle)?.name||'','cs')).map(b=>({id:b.id,date:b.date,vehicle:state.vehicles.find(v=>v.id===b.vehicle)?.name||'Vozidlo',plate:state.vehicles.find(v=>v.id===b.vehicle)?.plate||'',job:state.jobs.find(j=>j.id===b.job)?.name||'Zakázka',worker:state.workers.find(w=>w.id===drivers[b.id])?.name||'Řidič neurčen',hours:Number(b.hours)||0}));
}
export function installResourceReports(ctx){
 const dialog=document.createElement('dialog');dialog.className='operations-dialog resource-report';dialog.style.cssText='width:min(1100px,96vw);max-height:92dvh;overflow:auto';document.body.append(dialog);
 let mode='vacation',filters={},drivers={},epoch=0;
 const select=(key,title,rows)=>'<label>'+title+'<select name="'+key+'"><option value="">Všichni / vše</option>'+rows.map(x=>'<option value="'+esc(x.id)+'" '+(filters[key]===x.id?'selected':'')+'>'+esc(x.name)+'</option>').join('')+'</select></label>';
 function reset(){epoch++;dialog.close();dialog.replaceChildren();drivers={};filters={}}
 async function open(next){if(!ctx.manager())return;reset();mode=next;const day=pragueToday();filters={from:day.slice(0,7)+'-01',to:day,worker:'',job:'',vehicle:''};dialog.innerHTML='<p>Načítám aktuální výkaz…</p><button type="button" data-report-close>Zavřít</button>';dialog.showModal();const token=epoch;try{await ctx.refresh();if(token!==epoch||!ctx.manager())return;if(mode==='vehicles'){const data=await ctx.readDrivers();if(token!==epoch||!ctx.manager())return;drivers=Object.fromEntries(data.bookings.map(b=>[b.booking_id,b.driver_id]));}draw()}catch(e){if(token===epoch)dialog.innerHTML='<p role="alert">'+esc(e.message)+'</p><button type="button" data-report-close>Zavřít</button>'}}
 function rows(){if(filters.from&&filters.to&&filters.from>filters.to)return [];return mode==='vacation'?vacationRows(ctx.state(),filters):vehicleRows(ctx.state(),drivers,filters)}
 function draw(){const s=ctx.state(),vehicle=mode==='vehicles',list=rows();dialog.innerHTML='<header class="panel-heading"><h2>'+ (vehicle?'Výkaz aut a řidičů':'Výkaz dovolených')+'</h2><button type="button" data-report-close>Zavřít</button></header><p>'+(vehicle?'Rezervace vozidel v plánovači a jejich určení řidiči. Jde o plánované hodiny, nikoliv o knihu jízd nebo kilometry.':'Schválené dovolené podle data čerpání. Budoucí termíny jsou plánované; zamítnuté a zrušené žádosti nejsou zahrnuty.')+'</p><form class="form-grid" data-report-filter><label>Od<input name="from" type="date" value="'+esc(filters.from)+'"></label><label>Do<input name="to" type="date" value="'+esc(filters.to)+'"></label>'+select('worker',vehicle?'Řidič':'Pracovník',[...(vehicle?[{id:'none',name:'Řidič neurčen'}]:[]),...byName(s.workers)])+(vehicle?select('job','Zakázka',byName(s.jobs))+select('vehicle','Vozidlo',byName(s.vehicles)):'')+'<button type="submit">Použít filtry</button><button type="button" data-report-export>Export Excel</button></form>'+(filters.from&&filters.to&&filters.from>filters.to?'<p role="alert">Datum Od nesmí být po datu Do.</p>':'')+'<p>'+list.length+' záznamů · '+fmtHours(list.reduce((n,r)=>n+r.hours,0))+' h</p><div class="table-wrap"><table class="simple-table"><thead><tr>'+ (vehicle?['Datum','Vozidlo','SPZ','Zakázka','Řidič','Plánované hodiny']:['Datum','Pracovník','Hodiny dovolené']).map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+list.map(r=>'<tr>'+(vehicle?[r.date,r.vehicle,r.plate,r.job,r.worker,fmtHours(r.hours)]:[r.date,r.worker,fmtHours(r.hours)]).map(t=>'<td>'+esc(t)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'+(list.length?'':'<p>Pro vybrané filtry nejsou žádné záznamy.</p>')}
 dialog.addEventListener('submit',e=>{e.preventDefault();filters=Object.fromEntries(new FormData(e.target));draw()});
 dialog.addEventListener('click',e=>{if(e.target.closest('[data-report-close]'))return reset();if(e.target.closest('[data-report-export]')){const form=dialog.querySelector('form');filters=Object.fromEntries(new FormData(form));draw();if(filters.from&&filters.to&&filters.from>filters.to)return;const vehicle=mode==='vehicles';download(workbook(vehicle?['Datum','Vozidlo','SPZ','Zakázka','Řidič','Plánované hodiny']:['Datum','Pracovník','Hodiny dovolené'],rows().map(r=>vehicle?[r.date,r.vehicle,r.plate,r.job,r.worker,r.hours]:[r.date,r.worker,r.hours]),{name:vehicle?'Vozidla':'Dovolené',dateColumns:[0],numberColumns:[vehicle?5:2]}),vehicle?'vykaz-aut.xlsx':'vykaz-dovolenych.xlsx')}});
 dialog.addEventListener('cancel',reset);
 return {open,reset};
}
