import {defaultDriverMarkup} from './driver-labels.js?v=visible-drivers-1';
import {esc} from './data.js?v=overhead-unbilled-1';
import {byName} from './selection-order.js?v=selection-1';
export function installVehicleDrivers(ctx){
 const dialog=document.createElement('dialog');dialog.className='operations-dialog';document.body.append(dialog);let generation=0;
 function reset(){generation++;dialog.close();dialog.replaceChildren()}
 async function open(kind,id){if(!ctx.manager())return;reset();const token=generation;dialog.innerHTML='<p>Načítám řidiče…</p><button type="button" data-driver-close>Zavřít</button>';dialog.showModal();try{await ctx.refresh();const data=await ctx.read();if(token!==generation||!ctx.manager())return;const s=ctx.state(),booking=s.vehicleBookings.find(b=>b.id===id),vehicle=s.vehicles.find(v=>v.id===(kind==='default'?id:booking?.vehicle)),current=(kind==='default'?data.defaults.find(d=>d.vehicle_id===id):data.bookings.find(d=>d.booking_id===id))?.driver_id||'';if(!vehicle)throw Error('Vozidlo už není dostupné.');dialog.innerHTML='<form><h2>'+esc(vehicle.name)+' · '+(kind==='default'?'výchozí řidič':'řidič pro den a zakázku')+'</h2><p>'+(kind==='default'?'Předvyplní se do nových rezervací. Již uložený plán a historie se nezmění.':esc(booking.date)+' · '+esc(s.jobs.find(j=>j.id===booking.job)?.name||'Zakázka'))+'</p><label>Řidič<select name="driver"><option value="">Řidič neurčen</option>'+byName(s.workers).map(w=>'<option value="'+esc(w.id)+'" '+(w.id===current?'selected':'')+'>'+esc(w.name)+'</option>').join('')+'</select></label><p role="alert"></p><button type="submit">Uložit řidiče</button><button type="button" data-driver-close>Zavřít</button></form>';dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{await ctx.save(kind,{id,driver:e.target.driver.value},data.version);if(token===generation)reset()}catch(error){if(token===generation)dialog.querySelector('[role=alert]').textContent=error.message}finally{button.disabled=false}}}catch(e){if(token===generation)dialog.innerHTML='<p role="alert">'+esc(e.message)+'</p><button type="button" data-driver-close>Zavřít</button>'}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-driver-kind]');if(b){e.preventDefault();open(b.dataset.driverKind,b.dataset.driverId)}});
 dialog.addEventListener('click',e=>{if(e.target.closest('[data-driver-close]'))reset()});dialog.addEventListener('cancel',reset);
 function decorate(page){if(!ctx.manager())return;if(page==='vehicles')document.querySelectorAll('[data-action=vehicle][data-id]').forEach(b=>{if(b.dataset.id)b.insertAdjacentHTML('afterend',defaultDriverMarkup(ctx.state().vehicles.find(v=>v.id===b.dataset.id)||{})+'<button type="button" data-driver-kind="default" data-driver-id="'+esc(b.dataset.id)+'">Výchozí řidič</button>')});}
 return {decorate,open,reset};
}
